// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.op
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="device_dram_read_req_multiplexer,hls_ip_2017_4_op,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-2-i,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.458000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=234,HLS_SYN_LUT=339}" *)

module device_dram_read_req_multiplexer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
ap_continue,
        ap_idle,
        ap_ready,
        device_dram_req_context_V_id_din,
        device_dram_req_context_V_id_full_n,
        device_dram_req_context_V_id_write,
        device_dram_req_context_V_num_din,
        device_dram_req_context_V_num_full_n,
        device_dram_req_context_V_num_write,
        device_dram_read_req_V_num_din,
        device_dram_read_req_V_num_full_n,
        device_dram_read_req_V_num_write,
        device_dram_read_req_V_addr_din,
        device_dram_read_req_V_addr_full_n,
        device_dram_read_req_V_addr_write,
        device_dram_read_req_0_V_num_dout,
        device_dram_read_req_0_V_num_empty_n,
        device_dram_read_req_0_V_num_read,
        device_dram_read_req_0_V_addr_dout,
        device_dram_read_req_0_V_addr_empty_n,
        device_dram_read_req_0_V_addr_read,
        device_dram_read_req_1_V_num_dout,
        device_dram_read_req_1_V_num_empty_n,
        device_dram_read_req_1_V_num_read,
        device_dram_read_req_1_V_addr_dout,
        device_dram_read_req_1_V_addr_empty_n,
        device_dram_read_req_1_V_addr_read,
        device_dram_read_req_2_V_num_dout,
        device_dram_read_req_2_V_num_empty_n,
        device_dram_read_req_2_V_num_read,
        device_dram_read_req_2_V_addr_dout,
        device_dram_read_req_2_V_addr_empty_n,
        device_dram_read_req_2_V_addr_read
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output ap_ready; output ap_continue;
output  [7:0] device_dram_req_context_V_id_din;
input   device_dram_req_context_V_id_full_n;
output   device_dram_req_context_V_id_write;
output  [7:0] device_dram_req_context_V_num_din;
input   device_dram_req_context_V_num_full_n;
output   device_dram_req_context_V_num_write;
output  [7:0] device_dram_read_req_V_num_din;
input   device_dram_read_req_V_num_full_n;
output   device_dram_read_req_V_num_write;
output  [63:0] device_dram_read_req_V_addr_din;
input   device_dram_read_req_V_addr_full_n;
output   device_dram_read_req_V_addr_write;
input  [7:0] device_dram_read_req_0_V_num_dout;
input   device_dram_read_req_0_V_num_empty_n;
output   device_dram_read_req_0_V_num_read;
input  [63:0] device_dram_read_req_0_V_addr_dout;
input   device_dram_read_req_0_V_addr_empty_n;
output   device_dram_read_req_0_V_addr_read;
input  [7:0] device_dram_read_req_1_V_num_dout;
input   device_dram_read_req_1_V_num_empty_n;
output   device_dram_read_req_1_V_num_read;
input  [63:0] device_dram_read_req_1_V_addr_dout;
input   device_dram_read_req_1_V_addr_empty_n;
output   device_dram_read_req_1_V_addr_read;
input  [7:0] device_dram_read_req_2_V_num_dout;
input   device_dram_read_req_2_V_num_empty_n;
output   device_dram_read_req_2_V_num_read;
input  [63:0] device_dram_read_req_2_V_addr_dout;
input   device_dram_read_req_2_V_addr_empty_n;
output   device_dram_read_req_2_V_addr_read;

reg ap_idle;
reg[7:0] device_dram_req_context_V_id_din;
reg[7:0] device_dram_req_context_V_num_din;
reg[7:0] device_dram_read_req_V_num_din;
reg[63:0] device_dram_read_req_V_addr_din;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    device_dram_req_context_V_id_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_reg_360;
reg   [0:0] empty_n_9_reg_396;
reg   [0:0] empty_n_10_reg_400;
reg   [0:0] empty_n_12_reg_404;
reg   [0:0] tmp_2_reg_364;
reg   [0:0] empty_n_11_reg_384;
reg   [0:0] empty_n_13_reg_388;
reg   [0:0] empty_n_15_reg_392;
reg   [0:0] tmp_7_reg_368;
reg   [0:0] empty_n_14_reg_372;
reg   [0:0] empty_n_16_reg_376;
reg   [0:0] empty_n_17_reg_380;
reg    device_dram_req_context_V_num_blk_n;
reg    device_dram_read_req_V_num_blk_n;
reg    device_dram_read_req_V_addr_blk_n;
reg   [7:0] reg_288;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    device_dram_read_req_V_num1_status;
reg    ap_predicate_op88_write_state3;
wire    device_dram_req_context_V_id1_status;
reg    ap_predicate_op92_write_state3;
reg    ap_predicate_op96_write_state3;
reg    ap_predicate_op99_write_state3;
reg    ap_predicate_op103_write_state3;
reg    ap_predicate_op107_write_state3;
reg    ap_predicate_op110_write_state3;
reg    ap_predicate_op114_write_state3;
reg    ap_predicate_op118_write_state3;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_fu_324_p2;
wire   [0:0] tmp_2_fu_330_p2;
wire   [0:0] tmp_7_fu_336_p2;
wire   [0:0] grp_fu_276_p1;
wire   [0:0] empty_n_9_fu_260_p1;
reg   [63:0] reg_294;
reg   [7:0] reg_299;
wire   [0:0] grp_fu_244_p1;
reg   [63:0] reg_305;
reg   [7:0] reg_310;
wire   [0:0] grp_fu_256_p1;
reg   [63:0] reg_316;
reg    ap_block_pp0_stage0_subdone;
reg    device_dram_read_req_2_V_num0_update;
wire   [0:0] grp_nbread_fu_192_p3_0;
reg    device_dram_read_req_0_V_num0_update;
wire   [0:0] grp_nbread_fu_200_p3_0;
reg    device_dram_read_req_1_V_num0_update;
wire   [0:0] grp_nbread_fu_208_p3_0;
reg    device_dram_read_req_V_num1_update;
reg    ap_block_pp0_stage0_01001;
reg    device_dram_req_context_V_id1_update;
reg   [2:0] state_fu_188;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_324_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                state_fu_188[0] <= 1'b1;
        state_fu_188[1] <= 1'b0;
    end else if (((tmp_fu_324_p2 == 1'd0) & (tmp_2_fu_330_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                state_fu_188[0] <= 1'b0;
        state_fu_188[1] <= 1'b1;
    end else if ((((tmp_2_fu_330_p2 == 1'd0) & (tmp_fu_324_p2 == 1'd0) & (tmp_7_fu_336_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
                state_fu_188[0] <= 1'b0;
        state_fu_188[1] <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((empty_n_9_fu_260_p1 == 1'd0) & (tmp_fu_324_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        empty_n_10_reg_400 <= grp_nbread_fu_208_p3_0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_324_p2 == 1'd0) & (tmp_2_fu_330_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        empty_n_11_reg_384 <= grp_nbread_fu_208_p3_0;
    end
end

always @ (posedge ap_clk) begin
    if (((empty_n_9_fu_260_p1 == 1'd0) & (grp_fu_276_p1 == 1'd0) & (tmp_fu_324_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        empty_n_12_reg_404 <= grp_nbread_fu_192_p3_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fu_276_p1 == 1'd0) & (tmp_fu_324_p2 == 1'd0) & (tmp_2_fu_330_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        empty_n_13_reg_388 <= grp_nbread_fu_192_p3_0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_fu_330_p2 == 1'd0) & (tmp_fu_324_p2 == 1'd0) & (tmp_7_fu_336_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        empty_n_14_reg_372 <= grp_nbread_fu_192_p3_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fu_244_p1 == 1'd0) & (grp_fu_276_p1 == 1'd0) & (tmp_fu_324_p2 == 1'd0) & (tmp_2_fu_330_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        empty_n_15_reg_392 <= grp_nbread_fu_200_p3_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fu_244_p1 == 1'd0) & (tmp_2_fu_330_p2 == 1'd0) & (tmp_fu_324_p2 == 1'd0) & (tmp_7_fu_336_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        empty_n_16_reg_376 <= grp_nbread_fu_200_p3_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fu_256_p1 == 1'd0) & (grp_fu_244_p1 == 1'd0) & (tmp_2_fu_330_p2 == 1'd0) & (tmp_fu_324_p2 == 1'd0) & (tmp_7_fu_336_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_n_17_reg_380 <= grp_nbread_fu_208_p3_0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_324_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_n_9_reg_396 <= grp_nbread_fu_200_p3_0;
    end
end

always @ (posedge ap_clk) begin
    if ((((empty_n_9_fu_260_p1 == 1'd0) & (grp_fu_276_p1 == 1'd0) & (tmp_fu_324_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((grp_fu_276_p1 == 1'd0) & (tmp_fu_324_p2 == 1'd0) & (tmp_2_fu_330_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((tmp_2_fu_330_p2 == 1'd0) & (tmp_fu_324_p2 == 1'd0) & (tmp_7_fu_336_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
        reg_288 <= device_dram_read_req_2_V_num_dout;
        reg_294 <= device_dram_read_req_2_V_addr_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((((tmp_fu_324_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((grp_fu_244_p1 == 1'd0) & (grp_fu_276_p1 == 1'd0) & (tmp_fu_324_p2 == 1'd0) & (tmp_2_fu_330_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((grp_fu_244_p1 == 1'd0) & (tmp_2_fu_330_p2 == 1'd0) & (tmp_fu_324_p2 == 1'd0) & (tmp_7_fu_336_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
        reg_299 <= device_dram_read_req_0_V_num_dout;
        reg_305 <= device_dram_read_req_0_V_addr_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((((empty_n_9_fu_260_p1 == 1'd0) & (tmp_fu_324_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((tmp_fu_324_p2 == 1'd0) & (tmp_2_fu_330_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((grp_fu_256_p1 == 1'd0) & (grp_fu_244_p1 == 1'd0) & (tmp_2_fu_330_p2 == 1'd0) & (tmp_fu_324_p2 == 1'd0) & (tmp_7_fu_336_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
        reg_310 <= device_dram_read_req_1_V_num_dout;
        reg_316 <= device_dram_read_req_1_V_addr_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_324_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_2_reg_364 <= tmp_2_fu_330_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_fu_330_p2 == 1'd0) & (tmp_fu_324_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_7_reg_368 <= tmp_7_fu_336_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_reg_360 <= tmp_fu_324_p2;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((device_dram_read_req_0_V_num_empty_n & device_dram_read_req_0_V_addr_empty_n) == 1'b1) & (((tmp_fu_324_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((grp_fu_244_p1 == 1'd0) & (grp_fu_276_p1 == 1'd0) & (tmp_fu_324_p2 == 1'd0) & (tmp_2_fu_330_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((grp_fu_244_p1 == 1'd0) & (tmp_2_fu_330_p2 == 1'd0) & (tmp_fu_324_p2 == 1'd0) & (tmp_7_fu_336_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))))) begin
        device_dram_read_req_0_V_num0_update = 1'b1;
    end else begin
        device_dram_read_req_0_V_num0_update = 1'b0;
    end
end

always @ (*) begin
    if ((((device_dram_read_req_1_V_num_empty_n & device_dram_read_req_1_V_addr_empty_n) == 1'b1) & (((empty_n_9_fu_260_p1 == 1'd0) & (tmp_fu_324_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((tmp_fu_324_p2 == 1'd0) & (tmp_2_fu_330_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((grp_fu_256_p1 == 1'd0) & (grp_fu_244_p1 == 1'd0) & (tmp_2_fu_330_p2 == 1'd0) & (tmp_fu_324_p2 == 1'd0) & (tmp_7_fu_336_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))))) begin
        device_dram_read_req_1_V_num0_update = 1'b1;
    end else begin
        device_dram_read_req_1_V_num0_update = 1'b0;
    end
end

always @ (*) begin
    if ((((device_dram_read_req_2_V_num_empty_n & device_dram_read_req_2_V_addr_empty_n) == 1'b1) & (((empty_n_9_fu_260_p1 == 1'd0) & (grp_fu_276_p1 == 1'd0) & (tmp_fu_324_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((grp_fu_276_p1 == 1'd0) & (tmp_fu_324_p2 == 1'd0) & (tmp_2_fu_330_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((tmp_2_fu_330_p2 == 1'd0) & (tmp_fu_324_p2 == 1'd0) & (tmp_7_fu_336_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))))) begin
        device_dram_read_req_2_V_num0_update = 1'b1;
    end else begin
        device_dram_read_req_2_V_num0_update = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_reg_364 == 1'd0) & (empty_n_16_reg_376 == 1'd0) & (empty_n_14_reg_372 == 1'd0) & (empty_n_17_reg_380 == 1'd1) & (tmp_7_reg_368 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_2_reg_364 == 1'd0) & (empty_n_14_reg_372 == 1'd0) & (empty_n_16_reg_376 == 1'd1) & (tmp_7_reg_368 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_2_reg_364 == 1'd0) & (empty_n_14_reg_372 == 1'd1) & (tmp_7_reg_368 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_13_reg_388 == 1'd0) & (empty_n_11_reg_384 == 1'd0) & (tmp_2_reg_364 == 1'd1) & (empty_n_15_reg_392 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_11_reg_384 == 1'd0) & (tmp_2_reg_364 == 1'd1) & (empty_n_13_reg_388 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_2_reg_364 == 1'd1) & (empty_n_11_reg_384 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_10_reg_400 == 1'd0) & (empty_n_9_reg_396 == 1'd0) & (empty_n_12_reg_404 == 1'd1) & (tmp_reg_360 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_9_reg_396 == 1'd0) & (empty_n_10_reg_400 == 1'd1) & (tmp_reg_360 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_9_reg_396 == 1'd1) & (tmp_reg_360 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        device_dram_read_req_V_addr_blk_n = device_dram_read_req_V_addr_full_n;
    end else begin
        device_dram_read_req_V_addr_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op110_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op103_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op96_write_state3 == 1'b1)))) begin
        device_dram_read_req_V_addr_din = reg_294;
    end else if ((((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op118_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op99_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op92_write_state3 == 1'b1)))) begin
        device_dram_read_req_V_addr_din = reg_305;
    end else if ((((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op114_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op107_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op88_write_state3 == 1'b1)))) begin
        device_dram_read_req_V_addr_din = reg_316;
    end else begin
        device_dram_read_req_V_addr_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op118_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op114_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op110_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op107_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op103_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op99_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op96_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op92_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op88_write_state3 == 1'b1)))) begin
        device_dram_read_req_V_num1_update = 1'b1;
    end else begin
        device_dram_read_req_V_num1_update = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_reg_364 == 1'd0) & (empty_n_16_reg_376 == 1'd0) & (empty_n_14_reg_372 == 1'd0) & (empty_n_17_reg_380 == 1'd1) & (tmp_7_reg_368 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_2_reg_364 == 1'd0) & (empty_n_14_reg_372 == 1'd0) & (empty_n_16_reg_376 == 1'd1) & (tmp_7_reg_368 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_2_reg_364 == 1'd0) & (empty_n_14_reg_372 == 1'd1) & (tmp_7_reg_368 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_13_reg_388 == 1'd0) & (empty_n_11_reg_384 == 1'd0) & (tmp_2_reg_364 == 1'd1) & (empty_n_15_reg_392 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_11_reg_384 == 1'd0) & (tmp_2_reg_364 == 1'd1) & (empty_n_13_reg_388 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_2_reg_364 == 1'd1) & (empty_n_11_reg_384 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_10_reg_400 == 1'd0) & (empty_n_9_reg_396 == 1'd0) & (empty_n_12_reg_404 == 1'd1) & (tmp_reg_360 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_9_reg_396 == 1'd0) & (empty_n_10_reg_400 == 1'd1) & (tmp_reg_360 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_9_reg_396 == 1'd1) & (tmp_reg_360 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        device_dram_read_req_V_num_blk_n = device_dram_read_req_V_num_full_n;
    end else begin
        device_dram_read_req_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op110_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op103_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op96_write_state3 == 1'b1)))) begin
        device_dram_read_req_V_num_din = reg_288;
    end else if ((((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op118_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op99_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op92_write_state3 == 1'b1)))) begin
        device_dram_read_req_V_num_din = reg_299;
    end else if ((((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op114_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op107_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op88_write_state3 == 1'b1)))) begin
        device_dram_read_req_V_num_din = reg_310;
    end else begin
        device_dram_read_req_V_num_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op118_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op114_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op110_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op107_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op103_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op99_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op96_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op92_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op88_write_state3 == 1'b1)))) begin
        device_dram_req_context_V_id1_update = 1'b1;
    end else begin
        device_dram_req_context_V_id1_update = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_reg_364 == 1'd0) & (empty_n_16_reg_376 == 1'd0) & (empty_n_14_reg_372 == 1'd0) & (empty_n_17_reg_380 == 1'd1) & (tmp_7_reg_368 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_2_reg_364 == 1'd0) & (empty_n_14_reg_372 == 1'd0) & (empty_n_16_reg_376 == 1'd1) & (tmp_7_reg_368 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_2_reg_364 == 1'd0) & (empty_n_14_reg_372 == 1'd1) & (tmp_7_reg_368 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_13_reg_388 == 1'd0) & (empty_n_11_reg_384 == 1'd0) & (tmp_2_reg_364 == 1'd1) & (empty_n_15_reg_392 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_11_reg_384 == 1'd0) & (tmp_2_reg_364 == 1'd1) & (empty_n_13_reg_388 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_2_reg_364 == 1'd1) & (empty_n_11_reg_384 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_10_reg_400 == 1'd0) & (empty_n_9_reg_396 == 1'd0) & (empty_n_12_reg_404 == 1'd1) & (tmp_reg_360 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_9_reg_396 == 1'd0) & (empty_n_10_reg_400 == 1'd1) & (tmp_reg_360 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_9_reg_396 == 1'd1) & (tmp_reg_360 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        device_dram_req_context_V_id_blk_n = device_dram_req_context_V_id_full_n;
    end else begin
        device_dram_req_context_V_id_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op110_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op103_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op96_write_state3 == 1'b1)))) begin
        device_dram_req_context_V_id_din = 8'd2;
    end else if ((((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op118_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op99_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op92_write_state3 == 1'b1)))) begin
        device_dram_req_context_V_id_din = 8'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op114_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op107_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op88_write_state3 == 1'b1)))) begin
        device_dram_req_context_V_id_din = 8'd1;
    end else begin
        device_dram_req_context_V_id_din = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_2_reg_364 == 1'd0) & (empty_n_16_reg_376 == 1'd0) & (empty_n_14_reg_372 == 1'd0) & (empty_n_17_reg_380 == 1'd1) & (tmp_7_reg_368 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_2_reg_364 == 1'd0) & (empty_n_14_reg_372 == 1'd0) & (empty_n_16_reg_376 == 1'd1) & (tmp_7_reg_368 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_2_reg_364 == 1'd0) & (empty_n_14_reg_372 == 1'd1) & (tmp_7_reg_368 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_13_reg_388 == 1'd0) & (empty_n_11_reg_384 == 1'd0) & (tmp_2_reg_364 == 1'd1) & (empty_n_15_reg_392 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_11_reg_384 == 1'd0) & (tmp_2_reg_364 == 1'd1) & (empty_n_13_reg_388 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_2_reg_364 == 1'd1) & (empty_n_11_reg_384 == 1'd1) & (tmp_reg_360 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_10_reg_400 == 1'd0) & (empty_n_9_reg_396 == 1'd0) & (empty_n_12_reg_404 == 1'd1) & (tmp_reg_360 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_9_reg_396 == 1'd0) & (empty_n_10_reg_400 == 1'd1) & (tmp_reg_360 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_9_reg_396 == 1'd1) & (tmp_reg_360 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        device_dram_req_context_V_num_blk_n = device_dram_req_context_V_num_full_n;
    end else begin
        device_dram_req_context_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op110_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op103_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op96_write_state3 == 1'b1)))) begin
        device_dram_req_context_V_num_din = reg_288;
    end else if ((((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op118_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op99_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op92_write_state3 == 1'b1)))) begin
        device_dram_req_context_V_num_din = reg_299;
    end else if ((((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op114_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op107_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op88_write_state3 == 1'b1)))) begin
        device_dram_req_context_V_num_din = reg_310;
    end else begin
        device_dram_req_context_V_num_din = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op118_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op114_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op110_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op107_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op103_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op99_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op96_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op92_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op88_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op118_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op114_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op110_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op107_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op103_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op99_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op96_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op92_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op88_write_state3 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op118_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op114_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op110_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op107_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op103_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op99_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op96_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op92_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op88_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op118_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op114_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op110_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op107_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op103_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op99_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op96_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op92_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op88_write_state3 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op118_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op114_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op110_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op107_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op103_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op99_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op96_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op92_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op88_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op118_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op114_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op110_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op107_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op103_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op99_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op96_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op92_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op88_write_state3 == 1'b1))));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op118_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op114_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op110_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op107_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op103_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op99_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op96_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op92_write_state3 == 1'b1)) | ((device_dram_req_context_V_id1_status == 1'b0) & (ap_predicate_op88_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op118_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op114_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op110_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op107_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op103_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op99_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op96_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op92_write_state3 == 1'b1)) | ((device_dram_read_req_V_num1_status == 1'b0) & (ap_predicate_op88_write_state3 == 1'b1)));
end

assign ap_done = 1'b0;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op103_write_state3 = ((empty_n_11_reg_384 == 1'd0) & (tmp_2_reg_364 == 1'd1) & (empty_n_13_reg_388 == 1'd1) & (tmp_reg_360 == 1'd0));
end

always @ (*) begin
    ap_predicate_op107_write_state3 = ((tmp_2_reg_364 == 1'd1) & (empty_n_11_reg_384 == 1'd1) & (tmp_reg_360 == 1'd0));
end

always @ (*) begin
    ap_predicate_op110_write_state3 = ((empty_n_10_reg_400 == 1'd0) & (empty_n_9_reg_396 == 1'd0) & (empty_n_12_reg_404 == 1'd1) & (tmp_reg_360 == 1'd1));
end

always @ (*) begin
    ap_predicate_op114_write_state3 = ((empty_n_9_reg_396 == 1'd0) & (empty_n_10_reg_400 == 1'd1) & (tmp_reg_360 == 1'd1));
end

always @ (*) begin
    ap_predicate_op118_write_state3 = ((empty_n_9_reg_396 == 1'd1) & (tmp_reg_360 == 1'd1));
end

always @ (*) begin
    ap_predicate_op88_write_state3 = ((tmp_2_reg_364 == 1'd0) & (empty_n_16_reg_376 == 1'd0) & (empty_n_14_reg_372 == 1'd0) & (empty_n_17_reg_380 == 1'd1) & (tmp_7_reg_368 == 1'd1) & (tmp_reg_360 == 1'd0));
end

always @ (*) begin
    ap_predicate_op92_write_state3 = ((tmp_2_reg_364 == 1'd0) & (empty_n_14_reg_372 == 1'd0) & (empty_n_16_reg_376 == 1'd1) & (tmp_7_reg_368 == 1'd1) & (tmp_reg_360 == 1'd0));
end

always @ (*) begin
    ap_predicate_op96_write_state3 = ((tmp_2_reg_364 == 1'd0) & (empty_n_14_reg_372 == 1'd1) & (tmp_7_reg_368 == 1'd1) & (tmp_reg_360 == 1'd0));
end

always @ (*) begin
    ap_predicate_op99_write_state3 = ((empty_n_13_reg_388 == 1'd0) & (empty_n_11_reg_384 == 1'd0) & (tmp_2_reg_364 == 1'd1) & (empty_n_15_reg_392 == 1'd1) & (tmp_reg_360 == 1'd0));
end

assign ap_ready = 1'b0;

assign device_dram_read_req_0_V_addr_read = device_dram_read_req_0_V_num0_update;

assign device_dram_read_req_0_V_num_read = device_dram_read_req_0_V_num0_update;

assign device_dram_read_req_1_V_addr_read = device_dram_read_req_1_V_num0_update;

assign device_dram_read_req_1_V_num_read = device_dram_read_req_1_V_num0_update;

assign device_dram_read_req_2_V_addr_read = device_dram_read_req_2_V_num0_update;

assign device_dram_read_req_2_V_num_read = device_dram_read_req_2_V_num0_update;

assign device_dram_read_req_V_addr_write = device_dram_read_req_V_num1_update;

assign device_dram_read_req_V_num1_status = (device_dram_read_req_V_num_full_n & device_dram_read_req_V_addr_full_n);

assign device_dram_read_req_V_num_write = device_dram_read_req_V_num1_update;

assign device_dram_req_context_V_id1_status = (device_dram_req_context_V_num_full_n & device_dram_req_context_V_id_full_n);

assign device_dram_req_context_V_id_write = device_dram_req_context_V_id1_update;

assign device_dram_req_context_V_num_write = device_dram_req_context_V_id1_update;

assign empty_n_9_fu_260_p1 = grp_nbread_fu_200_p3_0;

assign grp_fu_244_p1 = grp_nbread_fu_192_p3_0;

assign grp_fu_256_p1 = grp_nbread_fu_200_p3_0;

assign grp_fu_276_p1 = grp_nbread_fu_208_p3_0;

assign grp_nbread_fu_192_p3_0 = (device_dram_read_req_2_V_num_empty_n & device_dram_read_req_2_V_addr_empty_n);

assign grp_nbread_fu_200_p3_0 = (device_dram_read_req_0_V_num_empty_n & device_dram_read_req_0_V_addr_empty_n);

assign grp_nbread_fu_208_p3_0 = (device_dram_read_req_1_V_num_empty_n & device_dram_read_req_1_V_addr_empty_n);

assign tmp_2_fu_330_p2 = ((state_fu_188 == 3'd1) ? 1'b1 : 1'b0);

assign tmp_7_fu_336_p2 = ((state_fu_188 == 3'd2) ? 1'b1 : 1'b0);

assign tmp_fu_324_p2 = ((state_fu_188 == 3'd0) ? 1'b1 : 1'b0);

always @ (posedge ap_clk) begin
    state_fu_188[2] <= 1'b0;
end

endmodule //device_dram_read_req_multiplexer
