// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="host_pipe0_dram_dispatcher,hls_ip_2017_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-2-i,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.290000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=815,HLS_SYN_LUT=4138}" *)

module host_pipe0_dram_dispatcher (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
ap_continue,
        ap_idle,
        ap_ready,
        host_dram_read_req_delayed_V_num_dout,
        host_dram_read_req_delayed_V_num_empty_n,
        host_dram_read_req_delayed_V_num_read,
        host_dram_read_req_delayed_V_addr_dout,
        host_dram_read_req_delayed_V_addr_empty_n,
        host_dram_read_req_delayed_V_addr_read,
        host_dram_write_req_apply_delayed_V_num_dout,
        host_dram_write_req_apply_delayed_V_num_empty_n,
        host_dram_write_req_apply_delayed_V_num_read,
        host_dram_write_req_apply_delayed_V_addr_dout,
        host_dram_write_req_apply_delayed_V_addr_empty_n,
        host_dram_write_req_apply_delayed_V_addr_read,
        host_dramA_read_req_V_num_din,
        host_dramA_read_req_V_num_full_n,
        host_dramA_read_req_V_num_write,
        host_dramA_read_req_V_addr_din,
        host_dramA_read_req_V_addr_full_n,
        host_dramA_read_req_V_addr_write,
        host_dramA_write_req_apply_V_num_din,
        host_dramA_write_req_apply_V_num_full_n,
        host_dramA_write_req_apply_V_num_write,
        host_dramA_write_req_apply_V_addr_din,
        host_dramA_write_req_apply_V_addr_full_n,
        host_dramA_write_req_apply_V_addr_write,
        host_dramB_read_req_V_num_din,
        host_dramB_read_req_V_num_full_n,
        host_dramB_read_req_V_num_write,
        host_dramB_read_req_V_addr_din,
        host_dramB_read_req_V_addr_full_n,
        host_dramB_read_req_V_addr_write,
        host_dramB_write_req_apply_V_num_din,
        host_dramB_write_req_apply_V_num_full_n,
        host_dramB_write_req_apply_V_num_write,
        host_dramB_write_req_apply_V_addr_din,
        host_dramB_write_req_apply_V_addr_full_n,
        host_dramB_write_req_apply_V_addr_write,
        host_dramC_read_req_V_num_din,
        host_dramC_read_req_V_num_full_n,
        host_dramC_read_req_V_num_write,
        host_dramC_read_req_V_addr_din,
        host_dramC_read_req_V_addr_full_n,
        host_dramC_read_req_V_addr_write,
        host_dramC_write_req_apply_V_num_din,
        host_dramC_write_req_apply_V_num_full_n,
        host_dramC_write_req_apply_V_num_write,
        host_dramC_write_req_apply_V_addr_din,
        host_dramC_write_req_apply_V_addr_full_n,
        host_dramC_write_req_apply_V_addr_write,
        host_dramD_read_req_V_num_din,
        host_dramD_read_req_V_num_full_n,
        host_dramD_read_req_V_num_write,
        host_dramD_read_req_V_addr_din,
        host_dramD_read_req_V_addr_full_n,
        host_dramD_read_req_V_addr_write,
        host_dramD_write_req_apply_V_num_din,
        host_dramD_write_req_apply_V_num_full_n,
        host_dramD_write_req_apply_V_num_write,
        host_dramD_write_req_apply_V_addr_din,
        host_dramD_write_req_apply_V_addr_full_n,
        host_dramD_write_req_apply_V_addr_write,
        host_dram_dispatcher_write_context_V_bank_id_din,
        host_dram_dispatcher_write_context_V_bank_id_full_n,
        host_dram_dispatcher_write_context_V_bank_id_write,
        host_dram_dispatcher_write_context_V_end_bank_id_din,
        host_dram_dispatcher_write_context_V_end_bank_id_full_n,
        host_dram_dispatcher_write_context_V_end_bank_id_write,
        host_dram_dispatcher_write_context_V_before_boundry_num_din,
        host_dram_dispatcher_write_context_V_before_boundry_num_full_n,
        host_dram_dispatcher_write_context_V_before_boundry_num_write,
        host_dram_dispatcher_write_context_V_cmd_num_din,
        host_dram_dispatcher_write_context_V_cmd_num_full_n,
        host_dram_dispatcher_write_context_V_cmd_num_write,
        host_dram_dispatcher_read_context_V_bank_id_din,
        host_dram_dispatcher_read_context_V_bank_id_full_n,
        host_dram_dispatcher_read_context_V_bank_id_write,
        host_dram_dispatcher_read_context_V_end_bank_id_din,
        host_dram_dispatcher_read_context_V_end_bank_id_full_n,
        host_dram_dispatcher_read_context_V_end_bank_id_write,
        host_dram_dispatcher_read_context_V_cmd_num_din,
        host_dram_dispatcher_read_context_V_cmd_num_full_n,
        host_dram_dispatcher_read_context_V_cmd_num_write,
        host_dram_write_resp_V_din,
        host_dram_write_resp_V_full_n,
        host_dram_write_resp_V_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output ap_ready; output ap_continue;
input  [7:0] host_dram_read_req_delayed_V_num_dout;
input   host_dram_read_req_delayed_V_num_empty_n;
output   host_dram_read_req_delayed_V_num_read;
input  [63:0] host_dram_read_req_delayed_V_addr_dout;
input   host_dram_read_req_delayed_V_addr_empty_n;
output   host_dram_read_req_delayed_V_addr_read;
input  [7:0] host_dram_write_req_apply_delayed_V_num_dout;
input   host_dram_write_req_apply_delayed_V_num_empty_n;
output   host_dram_write_req_apply_delayed_V_num_read;
input  [63:0] host_dram_write_req_apply_delayed_V_addr_dout;
input   host_dram_write_req_apply_delayed_V_addr_empty_n;
output   host_dram_write_req_apply_delayed_V_addr_read;
output  [7:0] host_dramA_read_req_V_num_din;
input   host_dramA_read_req_V_num_full_n;
output   host_dramA_read_req_V_num_write;
output  [63:0] host_dramA_read_req_V_addr_din;
input   host_dramA_read_req_V_addr_full_n;
output   host_dramA_read_req_V_addr_write;
output  [7:0] host_dramA_write_req_apply_V_num_din;
input   host_dramA_write_req_apply_V_num_full_n;
output   host_dramA_write_req_apply_V_num_write;
output  [63:0] host_dramA_write_req_apply_V_addr_din;
input   host_dramA_write_req_apply_V_addr_full_n;
output   host_dramA_write_req_apply_V_addr_write;
output  [7:0] host_dramB_read_req_V_num_din;
input   host_dramB_read_req_V_num_full_n;
output   host_dramB_read_req_V_num_write;
output  [63:0] host_dramB_read_req_V_addr_din;
input   host_dramB_read_req_V_addr_full_n;
output   host_dramB_read_req_V_addr_write;
output  [7:0] host_dramB_write_req_apply_V_num_din;
input   host_dramB_write_req_apply_V_num_full_n;
output   host_dramB_write_req_apply_V_num_write;
output  [63:0] host_dramB_write_req_apply_V_addr_din;
input   host_dramB_write_req_apply_V_addr_full_n;
output   host_dramB_write_req_apply_V_addr_write;
output  [7:0] host_dramC_read_req_V_num_din;
input   host_dramC_read_req_V_num_full_n;
output   host_dramC_read_req_V_num_write;
output  [63:0] host_dramC_read_req_V_addr_din;
input   host_dramC_read_req_V_addr_full_n;
output   host_dramC_read_req_V_addr_write;
output  [7:0] host_dramC_write_req_apply_V_num_din;
input   host_dramC_write_req_apply_V_num_full_n;
output   host_dramC_write_req_apply_V_num_write;
output  [63:0] host_dramC_write_req_apply_V_addr_din;
input   host_dramC_write_req_apply_V_addr_full_n;
output   host_dramC_write_req_apply_V_addr_write;
output  [7:0] host_dramD_read_req_V_num_din;
input   host_dramD_read_req_V_num_full_n;
output   host_dramD_read_req_V_num_write;
output  [63:0] host_dramD_read_req_V_addr_din;
input   host_dramD_read_req_V_addr_full_n;
output   host_dramD_read_req_V_addr_write;
output  [7:0] host_dramD_write_req_apply_V_num_din;
input   host_dramD_write_req_apply_V_num_full_n;
output   host_dramD_write_req_apply_V_num_write;
output  [63:0] host_dramD_write_req_apply_V_addr_din;
input   host_dramD_write_req_apply_V_addr_full_n;
output   host_dramD_write_req_apply_V_addr_write;
output  [7:0] host_dram_dispatcher_write_context_V_bank_id_din;
input   host_dram_dispatcher_write_context_V_bank_id_full_n;
output   host_dram_dispatcher_write_context_V_bank_id_write;
output  [7:0] host_dram_dispatcher_write_context_V_end_bank_id_din;
input   host_dram_dispatcher_write_context_V_end_bank_id_full_n;
output   host_dram_dispatcher_write_context_V_end_bank_id_write;
output  [31:0] host_dram_dispatcher_write_context_V_before_boundry_num_din;
input   host_dram_dispatcher_write_context_V_before_boundry_num_full_n;
output   host_dram_dispatcher_write_context_V_before_boundry_num_write;
output  [31:0] host_dram_dispatcher_write_context_V_cmd_num_din;
input   host_dram_dispatcher_write_context_V_cmd_num_full_n;
output   host_dram_dispatcher_write_context_V_cmd_num_write;
output  [7:0] host_dram_dispatcher_read_context_V_bank_id_din;
input   host_dram_dispatcher_read_context_V_bank_id_full_n;
output   host_dram_dispatcher_read_context_V_bank_id_write;
output  [7:0] host_dram_dispatcher_read_context_V_end_bank_id_din;
input   host_dram_dispatcher_read_context_V_end_bank_id_full_n;
output   host_dram_dispatcher_read_context_V_end_bank_id_write;
output  [31:0] host_dram_dispatcher_read_context_V_cmd_num_din;
input   host_dram_dispatcher_read_context_V_cmd_num_full_n;
output   host_dram_dispatcher_read_context_V_cmd_num_write;
output   host_dram_write_resp_V_din;
input   host_dram_write_resp_V_full_n;
output   host_dram_write_resp_V_write;

reg ap_idle;
reg[7:0] host_dram_dispatcher_write_context_V_end_bank_id_din;
reg[31:0] host_dram_dispatcher_write_context_V_before_boundry_num_din;
reg[7:0] host_dram_dispatcher_read_context_V_end_bank_id_din;
reg host_dram_write_resp_V_write;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    host_dramA_read_req_V_num_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] brmerge_reg_2637;
reg    host_dramA_read_req_V_addr_blk_n;
reg    host_dramA_write_req_apply_V_num_blk_n;
reg   [0:0] brmerge4_reg_2653;
reg    host_dramA_write_req_apply_V_addr_blk_n;
reg    host_dramB_read_req_V_num_blk_n;
reg   [0:0] brmerge1_reg_2641;
reg    host_dramB_read_req_V_addr_blk_n;
reg    host_dramB_write_req_apply_V_num_blk_n;
reg   [0:0] brmerge5_reg_2657;
reg    host_dramB_write_req_apply_V_addr_blk_n;
reg    host_dramC_read_req_V_num_blk_n;
reg   [0:0] brmerge2_reg_2645;
reg    host_dramC_read_req_V_addr_blk_n;
reg    host_dramC_write_req_apply_V_num_blk_n;
reg   [0:0] brmerge6_reg_2661;
reg    host_dramC_write_req_apply_V_addr_blk_n;
reg    host_dramD_read_req_V_num_blk_n;
reg   [0:0] brmerge3_reg_2649;
reg    host_dramD_read_req_V_addr_blk_n;
reg    host_dramD_write_req_apply_V_num_blk_n;
reg   [0:0] brmerge7_reg_2665;
reg    host_dramD_write_req_apply_V_addr_blk_n;
reg    host_dram_dispatcher_write_context_V_bank_id_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] empty_n_5_reg_2573;
reg   [0:0] tmp_12_reg_2628;
reg    host_dram_dispatcher_write_context_V_end_bank_id_blk_n;
reg    host_dram_dispatcher_write_context_V_before_boundry_num_blk_n;
reg    host_dram_dispatcher_write_context_V_cmd_num_blk_n;
reg    host_dram_dispatcher_read_context_V_bank_id_blk_n;
reg   [0:0] empty_n_4_reg_2509;
reg   [0:0] tmp_3_reg_2564;
reg    host_dram_dispatcher_read_context_V_end_bank_id_blk_n;
reg    host_dram_dispatcher_read_context_V_cmd_num_blk_n;
reg    host_dram_write_resp_V_blk_n;
wire   [0:0] empty_n_4_fu_733_p1;
wire    ap_block_state2_pp0_stage0_iter0;
wire    host_dram_dispatcher_read_context_V_bank_id1_status;
reg    ap_predicate_op203_write_state3;
reg    ap_predicate_op220_write_state3;
wire    host_dram_dispatcher_write_context_V_bank_id1_status;
reg    ap_predicate_op315_write_state3;
reg    ap_predicate_op332_write_state3;
reg    ap_block_state3_pp0_stage0_iter1;
wire    host_dramA_read_req_V_num1_status;
wire    host_dramB_read_req_V_num1_status;
wire    host_dramC_read_req_V_num1_status;
wire    host_dramD_read_req_V_num1_status;
wire    host_dramA_write_req_apply_V_num1_status;
wire    host_dramB_write_req_apply_V_num1_status;
wire    host_dramC_write_req_apply_V_num1_status;
wire    host_dramD_write_req_apply_V_num1_status;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [7:0] tmp_num_6_reg_2514;
wire   [11:0] tmp_fu_745_p1;
reg   [11:0] tmp_reg_2523;
wire   [1:0] read_bank_id_fu_749_p4;
reg   [1:0] read_bank_id_reg_2529;
wire   [7:0] tmp_bank_id_7_fu_759_p1;
reg   [7:0] tmp_bank_id_7_reg_2536;
reg   [49:0] tmp_1_reg_2542;
wire   [1:0] read_end_bank_id_fu_805_p4;
reg   [1:0] read_end_bank_id_reg_2547;
wire   [7:0] tmp_end_bank_id_2_fu_815_p1;
reg   [7:0] tmp_end_bank_id_2_reg_2554;
reg   [21:0] tmp_2_reg_2559;
wire   [0:0] tmp_3_fu_829_p2;
reg   [5:0] ddr_read_req_0_num_1_reg_2568;
wire   [0:0] empty_n_5_fu_870_p1;
reg   [7:0] tmp_num_7_reg_2578;
wire   [11:0] tmp_10_fu_882_p1;
reg   [11:0] tmp_10_reg_2587;
wire   [1:0] write_bank_id_fu_886_p4;
reg   [1:0] write_bank_id_reg_2593;
wire   [7:0] tmp_bank_id_11_fu_896_p1;
reg   [7:0] tmp_bank_id_11_reg_2600;
reg   [49:0] tmp_6_reg_2606;
wire   [1:0] write_end_bank_id_fu_942_p4;
reg   [1:0] write_end_bank_id_reg_2611;
wire   [7:0] tmp_end_bank_id_6_fu_952_p1;
reg   [7:0] tmp_end_bank_id_6_reg_2618;
reg   [21:0] tmp_11_reg_2623;
wire   [0:0] tmp_12_fu_966_p2;
reg   [5:0] ddr_write_apply_0_num_1_reg_2632;
wire   [0:0] brmerge_fu_1568_p2;
wire   [0:0] brmerge1_fu_1592_p2;
wire   [0:0] brmerge2_fu_1616_p2;
wire   [0:0] brmerge3_fu_1640_p2;
wire   [0:0] brmerge4_fu_2213_p2;
wire   [0:0] brmerge5_fu_2237_p2;
wire   [0:0] brmerge6_fu_2261_p2;
wire   [0:0] brmerge7_fu_2285_p2;
reg    ap_enable_reg_pp0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] ap_phi_precharge_reg_pp0_iter0_has_read_req1_reg_705;
reg   [0:0] ap_phi_precharge_reg_pp0_iter1_has_read_req1_reg_705;
wire   [0:0] ap_phi_precharge_reg_pp0_iter0_has_write_req1_reg_719;
reg   [0:0] ap_phi_precharge_reg_pp0_iter1_has_write_req1_reg_719;
reg    host_dram_read_req_delayed_V_num0_update;
wire   [0:0] empty_n_nbread_fu_572_p3_0;
reg    host_dram_write_req_apply_delayed_V_num0_update;
wire   [0:0] empty_n_1_nbread_fu_580_p3_0;
reg    host_dram_dispatcher_read_context_V_bank_id1_update;
reg    ap_block_pp0_stage0_01001;
reg    host_dram_dispatcher_write_context_V_bank_id1_update;
wire   [31:0] tmp_before_boundry_num_fu_2040_p1;
wire   [31:0] before_boundry_len_fu_1671_p1;
reg    host_dramA_read_req_V_num1_update;
reg    host_dramB_read_req_V_num1_update;
reg    host_dramC_read_req_V_num1_update;
reg    host_dramD_read_req_V_num1_update;
reg    host_dramA_write_req_apply_V_num1_update;
reg    host_dramB_write_req_apply_V_num1_update;
reg    host_dramC_write_req_apply_V_num1_update;
reg    host_dramD_write_req_apply_V_num1_update;
reg   [7:0] tmp_bank_id_fu_492;
reg   [7:0] tmp_bank_id_1_fu_496;
reg   [7:0] tmp_bank_id_2_fu_500;
reg   [7:0] tmp_bank_id_3_fu_504;
reg   [7:0] ddr_read_req_3_num_5_fu_508;
wire   [7:0] ddr_read_req_3_num_27_fu_1392_p3;
wire   [7:0] ddr_read_req_3_num_6_fu_1491_p3;
reg   [7:0] ddr_read_req_3_num_2_fu_512;
wire   [7:0] ddr_read_req_3_num_26_fu_1384_p3;
wire   [7:0] ddr_read_req_3_num_4_fu_1483_p3;
reg   [7:0] tmp_num_fu_516;
wire   [7:0] ddr_read_req_3_num_24_fu_1368_p3;
wire   [7:0] ddr_read_req_3_num_1_fu_1468_p3;
reg   [7:0] tmp_num_1_fu_520;
wire   [7:0] ddr_read_req_3_num_21_fu_1344_p3;
wire   [7:0] ddr_read_req_3_num_fu_1453_p3;
reg   [63:0] ddr_read_req_3_addr_9_fu_524;
wire   [63:0] ddr_read_req_3_addr_21_fu_1317_p3;
wire   [63:0] ddr_read_req_3_addr_11_fu_1126_p3;
reg   [63:0] ddr_read_req_3_addr_6_fu_528;
wire   [63:0] ddr_read_req_3_addr_20_fu_1309_p3;
wire   [63:0] ddr_read_req_3_addr_8_fu_1118_p3;
reg   [63:0] tmp_addr_fu_532;
wire   [63:0] ddr_read_req_3_addr_18_fu_1293_p3;
wire   [63:0] ddr_read_req_3_addr_5_fu_1102_p3;
reg   [63:0] tmp_addr_1_fu_536;
wire   [63:0] ddr_read_req_3_addr_15_fu_1269_p3;
wire   [63:0] ddr_read_req_3_addr_2_fu_1078_p3;
reg   [7:0] ddr_write_apply_3_num_5_fu_540;
wire   [7:0] ddr_write_apply_3_num_27_fu_2032_p3;
wire   [7:0] ddr_write_apply_3_num_6_fu_2136_p3;
reg   [7:0] ddr_write_apply_3_num_2_fu_544;
wire   [7:0] ddr_write_apply_3_num_26_fu_2024_p3;
wire   [7:0] ddr_write_apply_3_num_4_fu_2128_p3;
reg   [7:0] tmp_num_2_fu_548;
wire   [7:0] ddr_write_apply_3_num_24_fu_2008_p3;
wire   [7:0] ddr_write_apply_3_num_1_fu_2113_p3;
reg   [7:0] tmp_num_3_fu_552;
wire   [7:0] ddr_write_apply_3_num_21_fu_1984_p3;
wire   [7:0] ddr_write_apply_3_num_fu_2098_p3;
reg   [63:0] ddr_write_apply_3_addr_9_fu_556;
wire   [63:0] ddr_write_apply_3_addr_21_fu_1957_p3;
wire   [63:0] ddr_write_apply_3_addr_11_fu_1766_p3;
reg   [63:0] ddr_write_apply_3_addr_6_fu_560;
wire   [63:0] ddr_write_apply_3_addr_20_fu_1949_p3;
wire   [63:0] ddr_write_apply_3_addr_8_fu_1758_p3;
reg   [63:0] tmp_addr_2_fu_564;
wire   [63:0] ddr_write_apply_3_addr_18_fu_1933_p3;
wire   [63:0] ddr_write_apply_3_addr_5_fu_1742_p3;
reg   [63:0] tmp_addr_3_fu_568;
wire   [63:0] ddr_write_apply_3_addr_15_fu_1909_p3;
wire   [63:0] ddr_write_apply_3_addr_2_fu_1718_p3;
wire   [13:0] tmp_7_fu_773_p3;
wire   [14:0] tmp_9_cast_fu_785_p1;
wire   [14:0] tmp3_fu_789_p2;
wire   [35:0] tmp_8_fu_781_p1;
wire  signed [35:0] tmp241_cast_fu_795_p1;
wire   [35:0] end_addr_V_fu_799_p2;
wire   [36:0] lhs_V_cast_fu_840_p1;
wire   [36:0] r_V_fu_844_p2;
wire   [13:0] tmp_9_fu_910_p3;
wire   [14:0] tmp_23_cast_fu_922_p1;
wire   [14:0] tmp7_fu_926_p2;
wire   [35:0] tmp_15_fu_918_p1;
wire  signed [35:0] tmp242_cast_fu_932_p1;
wire   [35:0] end_addr_V_1_fu_936_p2;
wire   [36:0] lhs_V_2_cast_fu_977_p1;
wire   [36:0] r_V_1_fu_981_p2;
wire   [61:0] ddr_read_req_0_addr_fu_1022_p3;
wire   [33:0] ddr_read_req_0_addr_1_fu_1036_p3;
wire   [0:0] sel_tmp_fu_1047_p2;
wire   [63:0] ddr_read_req_0_addr_cast_fu_1028_p1;
wire   [0:0] sel_tmp2_fu_1060_p2;
wire   [63:0] ddr_read_req_3_addr_fu_1052_p3;
wire   [0:0] sel_tmp4_fu_1073_p2;
wire   [63:0] ddr_read_req_3_addr_1_fu_1065_p3;
wire   [63:0] ddr_read_req_3_addr_3_fu_1086_p3;
wire   [63:0] ddr_read_req_3_addr_4_fu_1094_p3;
wire   [63:0] ddr_read_req_3_addr_7_fu_1110_p3;
wire   [12:0] tmp_5_cast_fu_1019_p1;
wire   [12:0] tmp_4_fu_1146_p2;
wire   [6:0] tmp_5_fu_1152_p4;
wire   [7:0] ddr_read_req_0_num_fu_1162_p1;
wire   [7:0] ddr_read_req_3_num_8_fu_1166_p3;
wire   [7:0] ddr_read_req_3_num_9_fu_1174_p3;
wire   [7:0] ddr_read_req_3_num_12_fu_1190_p3;
wire   [7:0] ddr_read_req_3_num_13_fu_1198_p3;
wire   [7:0] ddr_read_req_3_num_15_fu_1214_p3;
wire   [0:0] sel_tmp1_fu_1238_p2;
wire   [63:0] ddr_read_req_0_addr_1_cast_fu_1043_p1;
wire   [0:0] sel_tmp3_fu_1251_p2;
wire   [63:0] ddr_read_req_3_addr_13_fu_1243_p3;
wire   [0:0] sel_tmp5_fu_1264_p2;
wire   [63:0] ddr_read_req_3_addr_14_fu_1256_p3;
wire   [63:0] ddr_read_req_3_addr_16_fu_1277_p3;
wire   [63:0] ddr_read_req_3_addr_17_fu_1285_p3;
wire   [63:0] ddr_read_req_3_addr_19_fu_1301_p3;
wire   [7:0] ddr_read_req_3_num_11_fu_1182_p3;
wire   [7:0] ddr_read_req_0_num_2_cast_fu_1325_p1;
wire   [7:0] ddr_read_req_3_num_19_fu_1328_p3;
wire   [7:0] ddr_read_req_3_num_20_fu_1336_p3;
wire   [7:0] ddr_read_req_3_num_14_fu_1206_p3;
wire   [7:0] ddr_read_req_3_num_22_fu_1352_p3;
wire   [7:0] ddr_read_req_3_num_23_fu_1360_p3;
wire   [7:0] ddr_read_req_3_num_16_fu_1222_p3;
wire   [7:0] ddr_read_req_3_num_25_fu_1376_p3;
wire   [7:0] ddr_read_req_3_num_17_fu_1230_p3;
wire   [0:0] or_cond_fu_1440_p2;
wire   [7:0] newSel_fu_1446_p3;
wire   [7:0] newSel2_fu_1461_p3;
wire   [7:0] ddr_read_req_3_num_3_fu_1476_p3;
wire   [0:0] notrhs_fu_1550_p2;
wire   [0:0] notlhs_fu_1544_p2;
wire   [0:0] or_cond_not_fu_1556_p2;
wire   [0:0] has_read_req_0_not_fu_1562_p2;
wire   [0:0] notrhs1_fu_1580_p2;
wire   [0:0] notlhs1_fu_1574_p2;
wire   [0:0] or_cond288_not_fu_1586_p2;
wire   [0:0] notrhs2_fu_1604_p2;
wire   [0:0] notlhs2_fu_1598_p2;
wire   [0:0] or_cond291_not_fu_1610_p2;
wire   [0:0] notrhs3_fu_1628_p2;
wire   [0:0] notlhs3_fu_1622_p2;
wire   [0:0] or_cond294_not_fu_1634_p2;
wire   [61:0] ddr_write_apply_0_addr_fu_1661_p3;
wire   [33:0] ddr_write_apply_0_addr_1_fu_1676_p3;
wire   [0:0] sel_tmp6_fu_1687_p2;
wire   [63:0] ddr_write_apply_0_addr_cast_fu_1667_p1;
wire   [0:0] sel_tmp7_fu_1700_p2;
wire   [63:0] ddr_write_apply_3_addr_fu_1692_p3;
wire   [0:0] sel_tmp8_fu_1713_p2;
wire   [63:0] ddr_write_apply_3_addr_1_fu_1705_p3;
wire   [63:0] ddr_write_apply_3_addr_3_fu_1726_p3;
wire   [63:0] ddr_write_apply_3_addr_4_fu_1734_p3;
wire   [63:0] ddr_write_apply_3_addr_7_fu_1750_p3;
wire   [12:0] tmp_20_cast_fu_1658_p1;
wire   [12:0] tmp_13_fu_1786_p2;
wire   [6:0] tmp_14_fu_1792_p4;
wire   [7:0] ddr_write_apply_0_num_fu_1802_p1;
wire   [7:0] ddr_write_apply_3_num_8_fu_1806_p3;
wire   [7:0] ddr_write_apply_3_num_9_fu_1814_p3;
wire   [7:0] ddr_write_apply_3_num_12_fu_1830_p3;
wire   [7:0] ddr_write_apply_3_num_13_fu_1838_p3;
wire   [7:0] ddr_write_apply_3_num_15_fu_1854_p3;
wire   [0:0] sel_tmp9_fu_1878_p2;
wire   [63:0] ddr_write_apply_0_addr_1_cast_fu_1683_p1;
wire   [0:0] sel_tmp10_fu_1891_p2;
wire   [63:0] ddr_write_apply_3_addr_13_fu_1883_p3;
wire   [0:0] sel_tmp11_fu_1904_p2;
wire   [63:0] ddr_write_apply_3_addr_14_fu_1896_p3;
wire   [63:0] ddr_write_apply_3_addr_16_fu_1917_p3;
wire   [63:0] ddr_write_apply_3_addr_17_fu_1925_p3;
wire   [63:0] ddr_write_apply_3_addr_19_fu_1941_p3;
wire   [7:0] ddr_write_apply_3_num_11_fu_1822_p3;
wire   [7:0] ddr_write_apply_0_num_2_cast_fu_1965_p1;
wire   [7:0] ddr_write_apply_3_num_19_fu_1968_p3;
wire   [7:0] ddr_write_apply_3_num_20_fu_1976_p3;
wire   [7:0] ddr_write_apply_3_num_14_fu_1846_p3;
wire   [7:0] ddr_write_apply_3_num_22_fu_1992_p3;
wire   [7:0] ddr_write_apply_3_num_23_fu_2000_p3;
wire   [7:0] ddr_write_apply_3_num_16_fu_1862_p3;
wire   [7:0] ddr_write_apply_3_num_25_fu_2016_p3;
wire   [7:0] ddr_write_apply_3_num_17_fu_1870_p3;
wire   [0:0] or_cond2_fu_2085_p2;
wire   [7:0] newSel4_fu_2091_p3;
wire   [7:0] newSel6_fu_2106_p3;
wire   [7:0] ddr_write_apply_3_num_3_fu_2121_p3;
wire   [0:0] notrhs4_fu_2195_p2;
wire   [0:0] notlhs4_fu_2189_p2;
wire   [0:0] or_cond297_not_fu_2201_p2;
wire   [0:0] has_write_req_0_not_fu_2207_p2;
wire   [0:0] notrhs5_fu_2225_p2;
wire   [0:0] notlhs5_fu_2219_p2;
wire   [0:0] or_cond299_not_fu_2231_p2;
wire   [0:0] notrhs6_fu_2249_p2;
wire   [0:0] notlhs6_fu_2243_p2;
wire   [0:0] or_cond302_not_fu_2255_p2;
wire   [0:0] notrhs7_fu_2273_p2;
wire   [0:0] notlhs7_fu_2267_p2;
wire   [0:0] or_cond305_not_fu_2279_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_365;
reg    ap_condition_408;
reg    ap_condition_486;
reg    ap_condition_479;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_subdone == 1'b0)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_subdone == 1'b0)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == empty_n_4_fu_733_p1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd1 == tmp_3_fu_829_p2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == empty_n_4_fu_733_p1) & (1'd0 == tmp_3_fu_829_p2) & (1'b1 == ap_enable_reg_pp0_iter0)))) begin
        ap_phi_precharge_reg_pp0_iter1_has_read_req1_reg_705 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == empty_n_4_fu_733_p1))) begin
        ap_phi_precharge_reg_pp0_iter1_has_read_req1_reg_705 <= empty_n_nbread_fu_572_p3_0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        ap_phi_precharge_reg_pp0_iter1_has_read_req1_reg_705 <= ap_phi_precharge_reg_pp0_iter0_has_read_req1_reg_705;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == empty_n_5_fu_870_p1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd1 == tmp_12_fu_966_p2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == empty_n_5_fu_870_p1) & (1'd0 == tmp_12_fu_966_p2) & (1'b1 == ap_enable_reg_pp0_iter0)))) begin
        ap_phi_precharge_reg_pp0_iter1_has_write_req1_reg_719 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == empty_n_5_fu_870_p1))) begin
        ap_phi_precharge_reg_pp0_iter1_has_write_req1_reg_719 <= empty_n_1_nbread_fu_580_p3_0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        ap_phi_precharge_reg_pp0_iter1_has_write_req1_reg_719 <= ap_phi_precharge_reg_pp0_iter0_has_write_req1_reg_719;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_365 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op220_write_state3)) begin
            ddr_read_req_3_addr_6_fu_528 <= ddr_read_req_3_addr_8_fu_1118_p3;
        end else if ((1'b1 == ap_predicate_op203_write_state3)) begin
            ddr_read_req_3_addr_6_fu_528 <= ddr_read_req_3_addr_20_fu_1309_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_365 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op220_write_state3)) begin
            ddr_read_req_3_addr_9_fu_524 <= ddr_read_req_3_addr_11_fu_1126_p3;
        end else if ((1'b1 == ap_predicate_op203_write_state3)) begin
            ddr_read_req_3_addr_9_fu_524 <= ddr_read_req_3_addr_21_fu_1317_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_365 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op220_write_state3)) begin
            ddr_read_req_3_num_2_fu_512 <= ddr_read_req_3_num_4_fu_1483_p3;
        end else if ((1'b1 == ap_predicate_op203_write_state3)) begin
            ddr_read_req_3_num_2_fu_512 <= ddr_read_req_3_num_26_fu_1384_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_365 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op220_write_state3)) begin
            ddr_read_req_3_num_5_fu_508 <= ddr_read_req_3_num_6_fu_1491_p3;
        end else if ((1'b1 == ap_predicate_op203_write_state3)) begin
            ddr_read_req_3_num_5_fu_508 <= ddr_read_req_3_num_27_fu_1392_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_365 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op332_write_state3)) begin
            ddr_write_apply_3_addr_6_fu_560 <= ddr_write_apply_3_addr_8_fu_1758_p3;
        end else if ((1'b1 == ap_predicate_op315_write_state3)) begin
            ddr_write_apply_3_addr_6_fu_560 <= ddr_write_apply_3_addr_20_fu_1949_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_365 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op332_write_state3)) begin
            ddr_write_apply_3_addr_9_fu_556 <= ddr_write_apply_3_addr_11_fu_1766_p3;
        end else if ((1'b1 == ap_predicate_op315_write_state3)) begin
            ddr_write_apply_3_addr_9_fu_556 <= ddr_write_apply_3_addr_21_fu_1957_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_365 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op332_write_state3)) begin
            ddr_write_apply_3_num_2_fu_544 <= ddr_write_apply_3_num_4_fu_2128_p3;
        end else if ((1'b1 == ap_predicate_op315_write_state3)) begin
            ddr_write_apply_3_num_2_fu_544 <= ddr_write_apply_3_num_26_fu_2024_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_365 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op332_write_state3)) begin
            ddr_write_apply_3_num_5_fu_540 <= ddr_write_apply_3_num_6_fu_2136_p3;
        end else if ((1'b1 == ap_predicate_op315_write_state3)) begin
            ddr_write_apply_3_num_5_fu_540 <= ddr_write_apply_3_num_27_fu_2032_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_365 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op220_write_state3)) begin
            tmp_addr_1_fu_536 <= ddr_read_req_3_addr_2_fu_1078_p3;
        end else if ((1'b1 == ap_predicate_op203_write_state3)) begin
            tmp_addr_1_fu_536 <= ddr_read_req_3_addr_15_fu_1269_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_365 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op332_write_state3)) begin
            tmp_addr_2_fu_564 <= ddr_write_apply_3_addr_5_fu_1742_p3;
        end else if ((1'b1 == ap_predicate_op315_write_state3)) begin
            tmp_addr_2_fu_564 <= ddr_write_apply_3_addr_18_fu_1933_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_365 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op332_write_state3)) begin
            tmp_addr_3_fu_568 <= ddr_write_apply_3_addr_2_fu_1718_p3;
        end else if ((1'b1 == ap_predicate_op315_write_state3)) begin
            tmp_addr_3_fu_568 <= ddr_write_apply_3_addr_15_fu_1909_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_365 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op220_write_state3)) begin
            tmp_addr_fu_532 <= ddr_read_req_3_addr_5_fu_1102_p3;
        end else if ((1'b1 == ap_predicate_op203_write_state3)) begin
            tmp_addr_fu_532 <= ddr_read_req_3_addr_18_fu_1293_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_486 == 1'b1)) begin
        if ((1'd1 == tmp_3_fu_829_p2)) begin
                        tmp_bank_id_2_fu_500[1 : 0] <= tmp_bank_id_7_fu_759_p1[1 : 0];
        end else if ((1'd0 == tmp_3_fu_829_p2)) begin
                        tmp_bank_id_2_fu_500[1 : 0] <= tmp_end_bank_id_2_fu_815_p1[1 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_479 == 1'b1)) begin
        if ((1'd1 == tmp_12_fu_966_p2)) begin
                        tmp_bank_id_fu_492[1 : 0] <= tmp_bank_id_11_fu_896_p1[1 : 0];
        end else if ((1'd0 == tmp_12_fu_966_p2)) begin
                        tmp_bank_id_fu_492[1 : 0] <= tmp_end_bank_id_6_fu_952_p1[1 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_365 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op220_write_state3)) begin
            tmp_num_1_fu_520 <= ddr_read_req_3_num_fu_1453_p3;
        end else if ((1'b1 == ap_predicate_op203_write_state3)) begin
            tmp_num_1_fu_520 <= ddr_read_req_3_num_21_fu_1344_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_365 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op332_write_state3)) begin
            tmp_num_2_fu_548 <= ddr_write_apply_3_num_1_fu_2113_p3;
        end else if ((1'b1 == ap_predicate_op315_write_state3)) begin
            tmp_num_2_fu_548 <= ddr_write_apply_3_num_24_fu_2008_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_365 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op332_write_state3)) begin
            tmp_num_3_fu_552 <= ddr_write_apply_3_num_fu_2098_p3;
        end else if ((1'b1 == ap_predicate_op315_write_state3)) begin
            tmp_num_3_fu_552 <= ddr_write_apply_3_num_21_fu_1984_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_365 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op220_write_state3)) begin
            tmp_num_fu_516 <= ddr_read_req_3_num_1_fu_1468_p3;
        end else if ((1'b1 == ap_predicate_op203_write_state3)) begin
            tmp_num_fu_516 <= ddr_read_req_3_num_24_fu_1368_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        brmerge1_reg_2641 <= brmerge1_fu_1592_p2;
        brmerge2_reg_2645 <= brmerge2_fu_1616_p2;
        brmerge3_reg_2649 <= brmerge3_fu_1640_p2;
        brmerge4_reg_2653 <= brmerge4_fu_2213_p2;
        brmerge5_reg_2657 <= brmerge5_fu_2237_p2;
        brmerge6_reg_2661 <= brmerge6_fu_2261_p2;
        brmerge7_reg_2665 <= brmerge7_fu_2285_p2;
        brmerge_reg_2637 <= brmerge_fu_1568_p2;
        empty_n_4_reg_2509 <= empty_n_nbread_fu_572_p3_0;
        empty_n_5_reg_2573 <= empty_n_1_nbread_fu_580_p3_0;
        tmp_10_reg_2587 <= tmp_10_fu_882_p1;
        tmp_num_6_reg_2514 <= host_dram_read_req_delayed_V_num_dout;
        tmp_num_7_reg_2578 <= host_dram_write_req_apply_delayed_V_num_dout;
        tmp_reg_2523 <= tmp_fu_745_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == empty_n_4_fu_733_p1) & (1'd0 == tmp_3_fu_829_p2))) begin
        ddr_read_req_0_num_1_reg_2568 <= {{r_V_fu_844_p2[11:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == empty_n_5_fu_870_p1) & (1'd0 == tmp_12_fu_966_p2))) begin
        ddr_write_apply_0_num_1_reg_2632 <= {{r_V_1_fu_981_p2[11:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == empty_n_4_fu_733_p1))) begin
        read_bank_id_reg_2529 <= {{host_dram_read_req_delayed_V_addr_dout[13:12]}};
        read_end_bank_id_reg_2547 <= {{end_addr_V_fu_799_p2[13:12]}};
        tmp_1_reg_2542 <= {{host_dram_read_req_delayed_V_addr_dout[63:14]}};
        tmp_2_reg_2559 <= {{end_addr_V_fu_799_p2[35:14]}};
        tmp_3_reg_2564 <= tmp_3_fu_829_p2;
        tmp_bank_id_7_reg_2536[1 : 0] <= tmp_bank_id_7_fu_759_p1[1 : 0];
        tmp_end_bank_id_2_reg_2554[1 : 0] <= tmp_end_bank_id_2_fu_815_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == empty_n_5_fu_870_p1))) begin
        tmp_11_reg_2623 <= {{end_addr_V_1_fu_936_p2[35:14]}};
        tmp_12_reg_2628 <= tmp_12_fu_966_p2;
        tmp_6_reg_2606 <= {{host_dram_write_req_apply_delayed_V_addr_dout[63:14]}};
        tmp_bank_id_11_reg_2600[1 : 0] <= tmp_bank_id_11_fu_896_p1[1 : 0];
        tmp_end_bank_id_6_reg_2618[1 : 0] <= tmp_end_bank_id_6_fu_952_p1[1 : 0];
        write_bank_id_reg_2593 <= {{host_dram_write_req_apply_delayed_V_addr_dout[13:12]}};
        write_end_bank_id_reg_2611 <= {{end_addr_V_1_fu_936_p2[13:12]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == empty_n_5_fu_870_p1) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        tmp_bank_id_1_fu_496[1 : 0] <= tmp_bank_id_11_fu_896_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == empty_n_4_fu_733_p1) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        tmp_bank_id_3_fu_504[1 : 0] <= tmp_bank_id_7_fu_759_p1[1 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1) & (1'b0 == ap_enable_reg_pp0_iter2))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (brmerge_reg_2637 == 1'd0))) begin
        host_dramA_read_req_V_addr_blk_n = host_dramA_read_req_V_addr_full_n;
    end else begin
        host_dramA_read_req_V_addr_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (brmerge_reg_2637 == 1'd0) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        host_dramA_read_req_V_num1_update = 1'b1;
    end else begin
        host_dramA_read_req_V_num1_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (brmerge_reg_2637 == 1'd0))) begin
        host_dramA_read_req_V_num_blk_n = host_dramA_read_req_V_num_full_n;
    end else begin
        host_dramA_read_req_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (1'd0 == brmerge4_reg_2653))) begin
        host_dramA_write_req_apply_V_addr_blk_n = host_dramA_write_req_apply_V_addr_full_n;
    end else begin
        host_dramA_write_req_apply_V_addr_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == brmerge4_reg_2653) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        host_dramA_write_req_apply_V_num1_update = 1'b1;
    end else begin
        host_dramA_write_req_apply_V_num1_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (1'd0 == brmerge4_reg_2653))) begin
        host_dramA_write_req_apply_V_num_blk_n = host_dramA_write_req_apply_V_num_full_n;
    end else begin
        host_dramA_write_req_apply_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (1'd0 == brmerge1_reg_2641))) begin
        host_dramB_read_req_V_addr_blk_n = host_dramB_read_req_V_addr_full_n;
    end else begin
        host_dramB_read_req_V_addr_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == brmerge1_reg_2641) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        host_dramB_read_req_V_num1_update = 1'b1;
    end else begin
        host_dramB_read_req_V_num1_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (1'd0 == brmerge1_reg_2641))) begin
        host_dramB_read_req_V_num_blk_n = host_dramB_read_req_V_num_full_n;
    end else begin
        host_dramB_read_req_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (1'd0 == brmerge5_reg_2657))) begin
        host_dramB_write_req_apply_V_addr_blk_n = host_dramB_write_req_apply_V_addr_full_n;
    end else begin
        host_dramB_write_req_apply_V_addr_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == brmerge5_reg_2657) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        host_dramB_write_req_apply_V_num1_update = 1'b1;
    end else begin
        host_dramB_write_req_apply_V_num1_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (1'd0 == brmerge5_reg_2657))) begin
        host_dramB_write_req_apply_V_num_blk_n = host_dramB_write_req_apply_V_num_full_n;
    end else begin
        host_dramB_write_req_apply_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (1'd0 == brmerge2_reg_2645))) begin
        host_dramC_read_req_V_addr_blk_n = host_dramC_read_req_V_addr_full_n;
    end else begin
        host_dramC_read_req_V_addr_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == brmerge2_reg_2645) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        host_dramC_read_req_V_num1_update = 1'b1;
    end else begin
        host_dramC_read_req_V_num1_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (1'd0 == brmerge2_reg_2645))) begin
        host_dramC_read_req_V_num_blk_n = host_dramC_read_req_V_num_full_n;
    end else begin
        host_dramC_read_req_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (1'd0 == brmerge6_reg_2661))) begin
        host_dramC_write_req_apply_V_addr_blk_n = host_dramC_write_req_apply_V_addr_full_n;
    end else begin
        host_dramC_write_req_apply_V_addr_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == brmerge6_reg_2661) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        host_dramC_write_req_apply_V_num1_update = 1'b1;
    end else begin
        host_dramC_write_req_apply_V_num1_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (1'd0 == brmerge6_reg_2661))) begin
        host_dramC_write_req_apply_V_num_blk_n = host_dramC_write_req_apply_V_num_full_n;
    end else begin
        host_dramC_write_req_apply_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (1'd0 == brmerge3_reg_2649))) begin
        host_dramD_read_req_V_addr_blk_n = host_dramD_read_req_V_addr_full_n;
    end else begin
        host_dramD_read_req_V_addr_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == brmerge3_reg_2649) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        host_dramD_read_req_V_num1_update = 1'b1;
    end else begin
        host_dramD_read_req_V_num1_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (1'd0 == brmerge3_reg_2649))) begin
        host_dramD_read_req_V_num_blk_n = host_dramD_read_req_V_num_full_n;
    end else begin
        host_dramD_read_req_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (1'd0 == brmerge7_reg_2665))) begin
        host_dramD_write_req_apply_V_addr_blk_n = host_dramD_write_req_apply_V_addr_full_n;
    end else begin
        host_dramD_write_req_apply_V_addr_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == brmerge7_reg_2665) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        host_dramD_write_req_apply_V_num1_update = 1'b1;
    end else begin
        host_dramD_write_req_apply_V_num1_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (1'd0 == brmerge7_reg_2665))) begin
        host_dramD_write_req_apply_V_num_blk_n = host_dramD_write_req_apply_V_num_full_n;
    end else begin
        host_dramD_write_req_apply_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_predicate_op203_write_state3) & (ap_block_pp0_stage0_11001 == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_predicate_op220_write_state3) & (ap_block_pp0_stage0_11001 == 1'b0)))) begin
        host_dram_dispatcher_read_context_V_bank_id1_update = 1'b1;
    end else begin
        host_dram_dispatcher_read_context_V_bank_id1_update = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == empty_n_4_reg_2509) & (1'd1 == tmp_3_reg_2564)) | ((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == empty_n_4_reg_2509) & (1'd0 == tmp_3_reg_2564)))) begin
        host_dram_dispatcher_read_context_V_bank_id_blk_n = host_dram_dispatcher_read_context_V_bank_id_full_n;
    end else begin
        host_dram_dispatcher_read_context_V_bank_id_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == empty_n_4_reg_2509) & (1'd1 == tmp_3_reg_2564)) | ((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == empty_n_4_reg_2509) & (1'd0 == tmp_3_reg_2564)))) begin
        host_dram_dispatcher_read_context_V_cmd_num_blk_n = host_dram_dispatcher_read_context_V_cmd_num_full_n;
    end else begin
        host_dram_dispatcher_read_context_V_cmd_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == empty_n_4_reg_2509) & (1'd1 == tmp_3_reg_2564)) | ((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == empty_n_4_reg_2509) & (1'd0 == tmp_3_reg_2564)))) begin
        host_dram_dispatcher_read_context_V_end_bank_id_blk_n = host_dram_dispatcher_read_context_V_end_bank_id_full_n;
    end else begin
        host_dram_dispatcher_read_context_V_end_bank_id_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((ap_condition_408 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op220_write_state3)) begin
            host_dram_dispatcher_read_context_V_end_bank_id_din = tmp_bank_id_7_reg_2536;
        end else if ((1'b1 == ap_predicate_op203_write_state3)) begin
            host_dram_dispatcher_read_context_V_end_bank_id_din = tmp_end_bank_id_2_reg_2554;
        end else begin
            host_dram_dispatcher_read_context_V_end_bank_id_din = 'bx;
        end
    end else begin
        host_dram_dispatcher_read_context_V_end_bank_id_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_predicate_op315_write_state3) & (ap_block_pp0_stage0_11001 == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_predicate_op332_write_state3) & (ap_block_pp0_stage0_11001 == 1'b0)))) begin
        host_dram_dispatcher_write_context_V_bank_id1_update = 1'b1;
    end else begin
        host_dram_dispatcher_write_context_V_bank_id1_update = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (empty_n_5_reg_2573 == 1'd1) & (1'd1 == tmp_12_reg_2628)) | ((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (empty_n_5_reg_2573 == 1'd1) & (1'd0 == tmp_12_reg_2628)))) begin
        host_dram_dispatcher_write_context_V_bank_id_blk_n = host_dram_dispatcher_write_context_V_bank_id_full_n;
    end else begin
        host_dram_dispatcher_write_context_V_bank_id_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (empty_n_5_reg_2573 == 1'd1) & (1'd1 == tmp_12_reg_2628)) | ((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (empty_n_5_reg_2573 == 1'd1) & (1'd0 == tmp_12_reg_2628)))) begin
        host_dram_dispatcher_write_context_V_before_boundry_num_blk_n = host_dram_dispatcher_write_context_V_before_boundry_num_full_n;
    end else begin
        host_dram_dispatcher_write_context_V_before_boundry_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((ap_condition_408 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op332_write_state3)) begin
            host_dram_dispatcher_write_context_V_before_boundry_num_din = before_boundry_len_fu_1671_p1;
        end else if ((1'b1 == ap_predicate_op315_write_state3)) begin
            host_dram_dispatcher_write_context_V_before_boundry_num_din = tmp_before_boundry_num_fu_2040_p1;
        end else begin
            host_dram_dispatcher_write_context_V_before_boundry_num_din = 'bx;
        end
    end else begin
        host_dram_dispatcher_write_context_V_before_boundry_num_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (empty_n_5_reg_2573 == 1'd1) & (1'd1 == tmp_12_reg_2628)) | ((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (empty_n_5_reg_2573 == 1'd1) & (1'd0 == tmp_12_reg_2628)))) begin
        host_dram_dispatcher_write_context_V_cmd_num_blk_n = host_dram_dispatcher_write_context_V_cmd_num_full_n;
    end else begin
        host_dram_dispatcher_write_context_V_cmd_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (empty_n_5_reg_2573 == 1'd1) & (1'd1 == tmp_12_reg_2628)) | ((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (empty_n_5_reg_2573 == 1'd1) & (1'd0 == tmp_12_reg_2628)))) begin
        host_dram_dispatcher_write_context_V_end_bank_id_blk_n = host_dram_dispatcher_write_context_V_end_bank_id_full_n;
    end else begin
        host_dram_dispatcher_write_context_V_end_bank_id_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((ap_condition_408 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op332_write_state3)) begin
            host_dram_dispatcher_write_context_V_end_bank_id_din = tmp_bank_id_11_reg_2600;
        end else if ((1'b1 == ap_predicate_op315_write_state3)) begin
            host_dram_dispatcher_write_context_V_end_bank_id_din = tmp_end_bank_id_6_reg_2618;
        end else begin
            host_dram_dispatcher_write_context_V_end_bank_id_din = 'bx;
        end
    end else begin
        host_dram_dispatcher_write_context_V_end_bank_id_din = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == (host_dram_read_req_delayed_V_num_empty_n & host_dram_read_req_delayed_V_addr_empty_n)))) begin
        host_dram_read_req_delayed_V_num0_update = 1'b1;
    end else begin
        host_dram_read_req_delayed_V_num0_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == (host_dram_write_req_apply_delayed_V_num_empty_n & host_dram_write_req_apply_delayed_V_addr_empty_n)))) begin
        host_dram_write_req_apply_delayed_V_num0_update = 1'b1;
    end else begin
        host_dram_write_req_apply_delayed_V_num0_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (empty_n_5_reg_2573 == 1'd1))) begin
        host_dram_write_resp_V_blk_n = host_dram_write_resp_V_full_n;
    end else begin
        host_dram_write_resp_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (empty_n_5_reg_2573 == 1'd1) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        host_dram_write_resp_V_write = 1'b1;
    end else begin
        host_dram_write_resp_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((1'b1 == ap_enable_reg_pp0_iter1) & (((1'b0 == host_dram_dispatcher_read_context_V_bank_id1_status) & (1'b1 == ap_predicate_op203_write_state3)) | ((1'b0 == host_dram_dispatcher_read_context_V_bank_id1_status) & (1'b1 == ap_predicate_op220_write_state3)) | ((empty_n_5_reg_2573 == 1'd1) & (1'b0 == host_dram_write_resp_V_full_n)) | ((1'b0 == host_dram_dispatcher_write_context_V_bank_id1_status) & (1'b1 == ap_predicate_op315_write_state3)) | ((1'b0 == host_dram_dispatcher_write_context_V_bank_id1_status) & (1'b1 == ap_predicate_op332_write_state3)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (((brmerge_reg_2637 == 1'd0) & (1'b0 == host_dramA_read_req_V_num1_status)) | ((1'd0 == brmerge1_reg_2641) & (1'b0 == host_dramB_read_req_V_num1_status)) | ((1'd0 == brmerge2_reg_2645) & (1'b0 == host_dramC_read_req_V_num1_status)) | ((1'd0 == brmerge3_reg_2649) & (1'b0 == host_dramD_read_req_V_num1_status)) | ((1'd0 == brmerge4_reg_2653) & (1'b0 == host_dramA_write_req_apply_V_num1_status)) | ((1'd0 == brmerge5_reg_2657) & (1'b0 == host_dramB_write_req_apply_V_num1_status)) | ((1'd0 == brmerge6_reg_2661) & (1'b0 == host_dramC_write_req_apply_V_num1_status)) | ((1'd0 == brmerge7_reg_2665) & (1'b0 == host_dramD_write_req_apply_V_num1_status)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_enable_reg_pp0_iter1) & (((1'b0 == host_dram_dispatcher_read_context_V_bank_id1_status) & (1'b1 == ap_predicate_op203_write_state3)) | ((1'b0 == host_dram_dispatcher_read_context_V_bank_id1_status) & (1'b1 == ap_predicate_op220_write_state3)) | ((empty_n_5_reg_2573 == 1'd1) & (1'b0 == host_dram_write_resp_V_full_n)) | ((1'b0 == host_dram_dispatcher_write_context_V_bank_id1_status) & (1'b1 == ap_predicate_op315_write_state3)) | ((1'b0 == host_dram_dispatcher_write_context_V_bank_id1_status) & (1'b1 == ap_predicate_op332_write_state3)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (((brmerge_reg_2637 == 1'd0) & (1'b0 == host_dramA_read_req_V_num1_status)) | ((1'd0 == brmerge1_reg_2641) & (1'b0 == host_dramB_read_req_V_num1_status)) | ((1'd0 == brmerge2_reg_2645) & (1'b0 == host_dramC_read_req_V_num1_status)) | ((1'd0 == brmerge3_reg_2649) & (1'b0 == host_dramD_read_req_V_num1_status)) | ((1'd0 == brmerge4_reg_2653) & (1'b0 == host_dramA_write_req_apply_V_num1_status)) | ((1'd0 == brmerge5_reg_2657) & (1'b0 == host_dramB_write_req_apply_V_num1_status)) | ((1'd0 == brmerge6_reg_2661) & (1'b0 == host_dramC_write_req_apply_V_num1_status)) | ((1'd0 == brmerge7_reg_2665) & (1'b0 == host_dramD_write_req_apply_V_num1_status)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_enable_reg_pp0_iter1) & (((1'b0 == host_dram_dispatcher_read_context_V_bank_id1_status) & (1'b1 == ap_predicate_op203_write_state3)) | ((1'b0 == host_dram_dispatcher_read_context_V_bank_id1_status) & (1'b1 == ap_predicate_op220_write_state3)) | ((empty_n_5_reg_2573 == 1'd1) & (1'b0 == host_dram_write_resp_V_full_n)) | ((1'b0 == host_dram_dispatcher_write_context_V_bank_id1_status) & (1'b1 == ap_predicate_op315_write_state3)) | ((1'b0 == host_dram_dispatcher_write_context_V_bank_id1_status) & (1'b1 == ap_predicate_op332_write_state3)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (((brmerge_reg_2637 == 1'd0) & (1'b0 == host_dramA_read_req_V_num1_status)) | ((1'd0 == brmerge1_reg_2641) & (1'b0 == host_dramB_read_req_V_num1_status)) | ((1'd0 == brmerge2_reg_2645) & (1'b0 == host_dramC_read_req_V_num1_status)) | ((1'd0 == brmerge3_reg_2649) & (1'b0 == host_dramD_read_req_V_num1_status)) | ((1'd0 == brmerge4_reg_2653) & (1'b0 == host_dramA_write_req_apply_V_num1_status)) | ((1'd0 == brmerge5_reg_2657) & (1'b0 == host_dramB_write_req_apply_V_num1_status)) | ((1'd0 == brmerge6_reg_2661) & (1'b0 == host_dramC_write_req_apply_V_num1_status)) | ((1'd0 == brmerge7_reg_2665) & (1'b0 == host_dramD_write_req_apply_V_num1_status)))));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((1'b0 == host_dram_dispatcher_read_context_V_bank_id1_status) & (1'b1 == ap_predicate_op203_write_state3)) | ((1'b0 == host_dram_dispatcher_read_context_V_bank_id1_status) & (1'b1 == ap_predicate_op220_write_state3)) | ((empty_n_5_reg_2573 == 1'd1) & (1'b0 == host_dram_write_resp_V_full_n)) | ((1'b0 == host_dram_dispatcher_write_context_V_bank_id1_status) & (1'b1 == ap_predicate_op315_write_state3)) | ((1'b0 == host_dram_dispatcher_write_context_V_bank_id1_status) & (1'b1 == ap_predicate_op332_write_state3)));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = (((brmerge_reg_2637 == 1'd0) & (1'b0 == host_dramA_read_req_V_num1_status)) | ((1'd0 == brmerge1_reg_2641) & (1'b0 == host_dramB_read_req_V_num1_status)) | ((1'd0 == brmerge2_reg_2645) & (1'b0 == host_dramC_read_req_V_num1_status)) | ((1'd0 == brmerge3_reg_2649) & (1'b0 == host_dramD_read_req_V_num1_status)) | ((1'd0 == brmerge4_reg_2653) & (1'b0 == host_dramA_write_req_apply_V_num1_status)) | ((1'd0 == brmerge5_reg_2657) & (1'b0 == host_dramB_write_req_apply_V_num1_status)) | ((1'd0 == brmerge6_reg_2661) & (1'b0 == host_dramC_write_req_apply_V_num1_status)) | ((1'd0 == brmerge7_reg_2665) & (1'b0 == host_dramD_write_req_apply_V_num1_status)));
end

always @ (*) begin
    ap_condition_365 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0));
end

always @ (*) begin
    ap_condition_408 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_01001 == 1'b0));
end

always @ (*) begin
    ap_condition_479 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == empty_n_5_fu_870_p1) & (1'b1 == ap_enable_reg_pp0_iter0));
end

always @ (*) begin
    ap_condition_486 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == empty_n_4_fu_733_p1) & (1'b1 == ap_enable_reg_pp0_iter0));
end

assign ap_done = 1'b0;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_precharge_reg_pp0_iter0_has_read_req1_reg_705 = 'bx;

assign ap_phi_precharge_reg_pp0_iter0_has_write_req1_reg_719 = 'bx;

always @ (*) begin
    ap_predicate_op203_write_state3 = ((1'd1 == empty_n_4_reg_2509) & (1'd0 == tmp_3_reg_2564));
end

always @ (*) begin
    ap_predicate_op220_write_state3 = ((1'd1 == empty_n_4_reg_2509) & (1'd1 == tmp_3_reg_2564));
end

always @ (*) begin
    ap_predicate_op315_write_state3 = ((empty_n_5_reg_2573 == 1'd1) & (1'd0 == tmp_12_reg_2628));
end

always @ (*) begin
    ap_predicate_op332_write_state3 = ((empty_n_5_reg_2573 == 1'd1) & (1'd1 == tmp_12_reg_2628));
end

assign ap_ready = 1'b0;

assign before_boundry_len_fu_1671_p1 = tmp_num_7_reg_2578;

assign brmerge1_fu_1592_p2 = (or_cond288_not_fu_1586_p2 | has_read_req_0_not_fu_1562_p2);

assign brmerge2_fu_1616_p2 = (or_cond291_not_fu_1610_p2 | has_read_req_0_not_fu_1562_p2);

assign brmerge3_fu_1640_p2 = (or_cond294_not_fu_1634_p2 | has_read_req_0_not_fu_1562_p2);

assign brmerge4_fu_2213_p2 = (or_cond297_not_fu_2201_p2 | has_write_req_0_not_fu_2207_p2);

assign brmerge5_fu_2237_p2 = (or_cond299_not_fu_2231_p2 | has_write_req_0_not_fu_2207_p2);

assign brmerge6_fu_2261_p2 = (or_cond302_not_fu_2255_p2 | has_write_req_0_not_fu_2207_p2);

assign brmerge7_fu_2285_p2 = (or_cond305_not_fu_2279_p2 | has_write_req_0_not_fu_2207_p2);

assign brmerge_fu_1568_p2 = (or_cond_not_fu_1556_p2 | has_read_req_0_not_fu_1562_p2);

assign ddr_read_req_0_addr_1_cast_fu_1043_p1 = ddr_read_req_0_addr_1_fu_1036_p3;

assign ddr_read_req_0_addr_1_fu_1036_p3 = {{tmp_2_reg_2559}, {12'd0}};

assign ddr_read_req_0_addr_cast_fu_1028_p1 = ddr_read_req_0_addr_fu_1022_p3;

assign ddr_read_req_0_addr_fu_1022_p3 = {{tmp_1_reg_2542}, {tmp_reg_2523}};

assign ddr_read_req_0_num_2_cast_fu_1325_p1 = ddr_read_req_0_num_1_reg_2568;

assign ddr_read_req_0_num_fu_1162_p1 = tmp_5_fu_1152_p4;

assign ddr_read_req_3_addr_11_fu_1126_p3 = ((sel_tmp4_fu_1073_p2[0:0] === 1'b1) ? ddr_read_req_0_addr_cast_fu_1028_p1 : ddr_read_req_3_addr_9_fu_524);

assign ddr_read_req_3_addr_13_fu_1243_p3 = ((sel_tmp1_fu_1238_p2[0:0] === 1'b1) ? ddr_read_req_3_addr_2_fu_1078_p3 : ddr_read_req_0_addr_1_cast_fu_1043_p1);

assign ddr_read_req_3_addr_14_fu_1256_p3 = ((sel_tmp3_fu_1251_p2[0:0] === 1'b1) ? ddr_read_req_3_addr_2_fu_1078_p3 : ddr_read_req_3_addr_13_fu_1243_p3);

assign ddr_read_req_3_addr_15_fu_1269_p3 = ((sel_tmp5_fu_1264_p2[0:0] === 1'b1) ? ddr_read_req_3_addr_2_fu_1078_p3 : ddr_read_req_3_addr_14_fu_1256_p3);

assign ddr_read_req_3_addr_16_fu_1277_p3 = ((sel_tmp1_fu_1238_p2[0:0] === 1'b1) ? ddr_read_req_0_addr_1_cast_fu_1043_p1 : ddr_read_req_3_addr_5_fu_1102_p3);

assign ddr_read_req_3_addr_17_fu_1285_p3 = ((sel_tmp3_fu_1251_p2[0:0] === 1'b1) ? ddr_read_req_3_addr_5_fu_1102_p3 : ddr_read_req_3_addr_16_fu_1277_p3);

assign ddr_read_req_3_addr_18_fu_1293_p3 = ((sel_tmp5_fu_1264_p2[0:0] === 1'b1) ? ddr_read_req_3_addr_5_fu_1102_p3 : ddr_read_req_3_addr_17_fu_1285_p3);

assign ddr_read_req_3_addr_19_fu_1301_p3 = ((sel_tmp3_fu_1251_p2[0:0] === 1'b1) ? ddr_read_req_0_addr_1_cast_fu_1043_p1 : ddr_read_req_3_addr_8_fu_1118_p3);

assign ddr_read_req_3_addr_1_fu_1065_p3 = ((sel_tmp2_fu_1060_p2[0:0] === 1'b1) ? tmp_addr_1_fu_536 : ddr_read_req_3_addr_fu_1052_p3);

assign ddr_read_req_3_addr_20_fu_1309_p3 = ((sel_tmp5_fu_1264_p2[0:0] === 1'b1) ? ddr_read_req_3_addr_8_fu_1118_p3 : ddr_read_req_3_addr_19_fu_1301_p3);

assign ddr_read_req_3_addr_21_fu_1317_p3 = ((sel_tmp5_fu_1264_p2[0:0] === 1'b1) ? ddr_read_req_0_addr_1_cast_fu_1043_p1 : ddr_read_req_3_addr_11_fu_1126_p3);

assign ddr_read_req_3_addr_2_fu_1078_p3 = ((sel_tmp4_fu_1073_p2[0:0] === 1'b1) ? tmp_addr_1_fu_536 : ddr_read_req_3_addr_1_fu_1065_p3);

assign ddr_read_req_3_addr_3_fu_1086_p3 = ((sel_tmp_fu_1047_p2[0:0] === 1'b1) ? ddr_read_req_0_addr_cast_fu_1028_p1 : tmp_addr_fu_532);

assign ddr_read_req_3_addr_4_fu_1094_p3 = ((sel_tmp2_fu_1060_p2[0:0] === 1'b1) ? tmp_addr_fu_532 : ddr_read_req_3_addr_3_fu_1086_p3);

assign ddr_read_req_3_addr_5_fu_1102_p3 = ((sel_tmp4_fu_1073_p2[0:0] === 1'b1) ? tmp_addr_fu_532 : ddr_read_req_3_addr_4_fu_1094_p3);

assign ddr_read_req_3_addr_7_fu_1110_p3 = ((sel_tmp2_fu_1060_p2[0:0] === 1'b1) ? ddr_read_req_0_addr_cast_fu_1028_p1 : ddr_read_req_3_addr_6_fu_528);

assign ddr_read_req_3_addr_8_fu_1118_p3 = ((sel_tmp4_fu_1073_p2[0:0] === 1'b1) ? ddr_read_req_3_addr_6_fu_528 : ddr_read_req_3_addr_7_fu_1110_p3);

assign ddr_read_req_3_addr_fu_1052_p3 = ((sel_tmp_fu_1047_p2[0:0] === 1'b1) ? tmp_addr_1_fu_536 : ddr_read_req_0_addr_cast_fu_1028_p1);

assign ddr_read_req_3_num_11_fu_1182_p3 = ((sel_tmp4_fu_1073_p2[0:0] === 1'b1) ? tmp_num_1_fu_520 : ddr_read_req_3_num_9_fu_1174_p3);

assign ddr_read_req_3_num_12_fu_1190_p3 = ((sel_tmp_fu_1047_p2[0:0] === 1'b1) ? ddr_read_req_0_num_fu_1162_p1 : tmp_num_fu_516);

assign ddr_read_req_3_num_13_fu_1198_p3 = ((sel_tmp2_fu_1060_p2[0:0] === 1'b1) ? tmp_num_fu_516 : ddr_read_req_3_num_12_fu_1190_p3);

assign ddr_read_req_3_num_14_fu_1206_p3 = ((sel_tmp4_fu_1073_p2[0:0] === 1'b1) ? tmp_num_fu_516 : ddr_read_req_3_num_13_fu_1198_p3);

assign ddr_read_req_3_num_15_fu_1214_p3 = ((sel_tmp2_fu_1060_p2[0:0] === 1'b1) ? ddr_read_req_0_num_fu_1162_p1 : ddr_read_req_3_num_2_fu_512);

assign ddr_read_req_3_num_16_fu_1222_p3 = ((sel_tmp4_fu_1073_p2[0:0] === 1'b1) ? ddr_read_req_3_num_2_fu_512 : ddr_read_req_3_num_15_fu_1214_p3);

assign ddr_read_req_3_num_17_fu_1230_p3 = ((sel_tmp4_fu_1073_p2[0:0] === 1'b1) ? ddr_read_req_0_num_fu_1162_p1 : ddr_read_req_3_num_5_fu_508);

assign ddr_read_req_3_num_19_fu_1328_p3 = ((sel_tmp1_fu_1238_p2[0:0] === 1'b1) ? ddr_read_req_3_num_11_fu_1182_p3 : ddr_read_req_0_num_2_cast_fu_1325_p1);

assign ddr_read_req_3_num_1_fu_1468_p3 = ((or_cond_fu_1440_p2[0:0] === 1'b1) ? tmp_num_fu_516 : newSel2_fu_1461_p3);

assign ddr_read_req_3_num_20_fu_1336_p3 = ((sel_tmp3_fu_1251_p2[0:0] === 1'b1) ? ddr_read_req_3_num_11_fu_1182_p3 : ddr_read_req_3_num_19_fu_1328_p3);

assign ddr_read_req_3_num_21_fu_1344_p3 = ((sel_tmp5_fu_1264_p2[0:0] === 1'b1) ? ddr_read_req_3_num_11_fu_1182_p3 : ddr_read_req_3_num_20_fu_1336_p3);

assign ddr_read_req_3_num_22_fu_1352_p3 = ((sel_tmp1_fu_1238_p2[0:0] === 1'b1) ? ddr_read_req_0_num_2_cast_fu_1325_p1 : ddr_read_req_3_num_14_fu_1206_p3);

assign ddr_read_req_3_num_23_fu_1360_p3 = ((sel_tmp3_fu_1251_p2[0:0] === 1'b1) ? ddr_read_req_3_num_14_fu_1206_p3 : ddr_read_req_3_num_22_fu_1352_p3);

assign ddr_read_req_3_num_24_fu_1368_p3 = ((sel_tmp5_fu_1264_p2[0:0] === 1'b1) ? ddr_read_req_3_num_14_fu_1206_p3 : ddr_read_req_3_num_23_fu_1360_p3);

assign ddr_read_req_3_num_25_fu_1376_p3 = ((sel_tmp3_fu_1251_p2[0:0] === 1'b1) ? ddr_read_req_0_num_2_cast_fu_1325_p1 : ddr_read_req_3_num_16_fu_1222_p3);

assign ddr_read_req_3_num_26_fu_1384_p3 = ((sel_tmp5_fu_1264_p2[0:0] === 1'b1) ? ddr_read_req_3_num_16_fu_1222_p3 : ddr_read_req_3_num_25_fu_1376_p3);

assign ddr_read_req_3_num_27_fu_1392_p3 = ((sel_tmp5_fu_1264_p2[0:0] === 1'b1) ? ddr_read_req_0_num_2_cast_fu_1325_p1 : ddr_read_req_3_num_17_fu_1230_p3);

assign ddr_read_req_3_num_3_fu_1476_p3 = ((sel_tmp2_fu_1060_p2[0:0] === 1'b1) ? tmp_num_6_reg_2514 : ddr_read_req_3_num_2_fu_512);

assign ddr_read_req_3_num_4_fu_1483_p3 = ((sel_tmp4_fu_1073_p2[0:0] === 1'b1) ? ddr_read_req_3_num_2_fu_512 : ddr_read_req_3_num_3_fu_1476_p3);

assign ddr_read_req_3_num_6_fu_1491_p3 = ((sel_tmp4_fu_1073_p2[0:0] === 1'b1) ? tmp_num_6_reg_2514 : ddr_read_req_3_num_5_fu_508);

assign ddr_read_req_3_num_8_fu_1166_p3 = ((sel_tmp_fu_1047_p2[0:0] === 1'b1) ? tmp_num_1_fu_520 : ddr_read_req_0_num_fu_1162_p1);

assign ddr_read_req_3_num_9_fu_1174_p3 = ((sel_tmp2_fu_1060_p2[0:0] === 1'b1) ? tmp_num_1_fu_520 : ddr_read_req_3_num_8_fu_1166_p3);

assign ddr_read_req_3_num_fu_1453_p3 = ((or_cond_fu_1440_p2[0:0] === 1'b1) ? tmp_num_1_fu_520 : newSel_fu_1446_p3);

assign ddr_write_apply_0_addr_1_cast_fu_1683_p1 = ddr_write_apply_0_addr_1_fu_1676_p3;

assign ddr_write_apply_0_addr_1_fu_1676_p3 = {{tmp_11_reg_2623}, {12'd0}};

assign ddr_write_apply_0_addr_cast_fu_1667_p1 = ddr_write_apply_0_addr_fu_1661_p3;

assign ddr_write_apply_0_addr_fu_1661_p3 = {{tmp_6_reg_2606}, {tmp_10_reg_2587}};

assign ddr_write_apply_0_num_2_cast_fu_1965_p1 = ddr_write_apply_0_num_1_reg_2632;

assign ddr_write_apply_0_num_fu_1802_p1 = tmp_14_fu_1792_p4;

assign ddr_write_apply_3_addr_11_fu_1766_p3 = ((sel_tmp8_fu_1713_p2[0:0] === 1'b1) ? ddr_write_apply_0_addr_cast_fu_1667_p1 : ddr_write_apply_3_addr_9_fu_556);

assign ddr_write_apply_3_addr_13_fu_1883_p3 = ((sel_tmp9_fu_1878_p2[0:0] === 1'b1) ? ddr_write_apply_3_addr_2_fu_1718_p3 : ddr_write_apply_0_addr_1_cast_fu_1683_p1);

assign ddr_write_apply_3_addr_14_fu_1896_p3 = ((sel_tmp10_fu_1891_p2[0:0] === 1'b1) ? ddr_write_apply_3_addr_2_fu_1718_p3 : ddr_write_apply_3_addr_13_fu_1883_p3);

assign ddr_write_apply_3_addr_15_fu_1909_p3 = ((sel_tmp11_fu_1904_p2[0:0] === 1'b1) ? ddr_write_apply_3_addr_2_fu_1718_p3 : ddr_write_apply_3_addr_14_fu_1896_p3);

assign ddr_write_apply_3_addr_16_fu_1917_p3 = ((sel_tmp9_fu_1878_p2[0:0] === 1'b1) ? ddr_write_apply_0_addr_1_cast_fu_1683_p1 : ddr_write_apply_3_addr_5_fu_1742_p3);

assign ddr_write_apply_3_addr_17_fu_1925_p3 = ((sel_tmp10_fu_1891_p2[0:0] === 1'b1) ? ddr_write_apply_3_addr_5_fu_1742_p3 : ddr_write_apply_3_addr_16_fu_1917_p3);

assign ddr_write_apply_3_addr_18_fu_1933_p3 = ((sel_tmp11_fu_1904_p2[0:0] === 1'b1) ? ddr_write_apply_3_addr_5_fu_1742_p3 : ddr_write_apply_3_addr_17_fu_1925_p3);

assign ddr_write_apply_3_addr_19_fu_1941_p3 = ((sel_tmp10_fu_1891_p2[0:0] === 1'b1) ? ddr_write_apply_0_addr_1_cast_fu_1683_p1 : ddr_write_apply_3_addr_8_fu_1758_p3);

assign ddr_write_apply_3_addr_1_fu_1705_p3 = ((sel_tmp7_fu_1700_p2[0:0] === 1'b1) ? tmp_addr_3_fu_568 : ddr_write_apply_3_addr_fu_1692_p3);

assign ddr_write_apply_3_addr_20_fu_1949_p3 = ((sel_tmp11_fu_1904_p2[0:0] === 1'b1) ? ddr_write_apply_3_addr_8_fu_1758_p3 : ddr_write_apply_3_addr_19_fu_1941_p3);

assign ddr_write_apply_3_addr_21_fu_1957_p3 = ((sel_tmp11_fu_1904_p2[0:0] === 1'b1) ? ddr_write_apply_0_addr_1_cast_fu_1683_p1 : ddr_write_apply_3_addr_11_fu_1766_p3);

assign ddr_write_apply_3_addr_2_fu_1718_p3 = ((sel_tmp8_fu_1713_p2[0:0] === 1'b1) ? tmp_addr_3_fu_568 : ddr_write_apply_3_addr_1_fu_1705_p3);

assign ddr_write_apply_3_addr_3_fu_1726_p3 = ((sel_tmp6_fu_1687_p2[0:0] === 1'b1) ? ddr_write_apply_0_addr_cast_fu_1667_p1 : tmp_addr_2_fu_564);

assign ddr_write_apply_3_addr_4_fu_1734_p3 = ((sel_tmp7_fu_1700_p2[0:0] === 1'b1) ? tmp_addr_2_fu_564 : ddr_write_apply_3_addr_3_fu_1726_p3);

assign ddr_write_apply_3_addr_5_fu_1742_p3 = ((sel_tmp8_fu_1713_p2[0:0] === 1'b1) ? tmp_addr_2_fu_564 : ddr_write_apply_3_addr_4_fu_1734_p3);

assign ddr_write_apply_3_addr_7_fu_1750_p3 = ((sel_tmp7_fu_1700_p2[0:0] === 1'b1) ? ddr_write_apply_0_addr_cast_fu_1667_p1 : ddr_write_apply_3_addr_6_fu_560);

assign ddr_write_apply_3_addr_8_fu_1758_p3 = ((sel_tmp8_fu_1713_p2[0:0] === 1'b1) ? ddr_write_apply_3_addr_6_fu_560 : ddr_write_apply_3_addr_7_fu_1750_p3);

assign ddr_write_apply_3_addr_fu_1692_p3 = ((sel_tmp6_fu_1687_p2[0:0] === 1'b1) ? tmp_addr_3_fu_568 : ddr_write_apply_0_addr_cast_fu_1667_p1);

assign ddr_write_apply_3_num_11_fu_1822_p3 = ((sel_tmp8_fu_1713_p2[0:0] === 1'b1) ? tmp_num_3_fu_552 : ddr_write_apply_3_num_9_fu_1814_p3);

assign ddr_write_apply_3_num_12_fu_1830_p3 = ((sel_tmp6_fu_1687_p2[0:0] === 1'b1) ? ddr_write_apply_0_num_fu_1802_p1 : tmp_num_2_fu_548);

assign ddr_write_apply_3_num_13_fu_1838_p3 = ((sel_tmp7_fu_1700_p2[0:0] === 1'b1) ? tmp_num_2_fu_548 : ddr_write_apply_3_num_12_fu_1830_p3);

assign ddr_write_apply_3_num_14_fu_1846_p3 = ((sel_tmp8_fu_1713_p2[0:0] === 1'b1) ? tmp_num_2_fu_548 : ddr_write_apply_3_num_13_fu_1838_p3);

assign ddr_write_apply_3_num_15_fu_1854_p3 = ((sel_tmp7_fu_1700_p2[0:0] === 1'b1) ? ddr_write_apply_0_num_fu_1802_p1 : ddr_write_apply_3_num_2_fu_544);

assign ddr_write_apply_3_num_16_fu_1862_p3 = ((sel_tmp8_fu_1713_p2[0:0] === 1'b1) ? ddr_write_apply_3_num_2_fu_544 : ddr_write_apply_3_num_15_fu_1854_p3);

assign ddr_write_apply_3_num_17_fu_1870_p3 = ((sel_tmp8_fu_1713_p2[0:0] === 1'b1) ? ddr_write_apply_0_num_fu_1802_p1 : ddr_write_apply_3_num_5_fu_540);

assign ddr_write_apply_3_num_19_fu_1968_p3 = ((sel_tmp9_fu_1878_p2[0:0] === 1'b1) ? ddr_write_apply_3_num_11_fu_1822_p3 : ddr_write_apply_0_num_2_cast_fu_1965_p1);

assign ddr_write_apply_3_num_1_fu_2113_p3 = ((or_cond2_fu_2085_p2[0:0] === 1'b1) ? tmp_num_2_fu_548 : newSel6_fu_2106_p3);

assign ddr_write_apply_3_num_20_fu_1976_p3 = ((sel_tmp10_fu_1891_p2[0:0] === 1'b1) ? ddr_write_apply_3_num_11_fu_1822_p3 : ddr_write_apply_3_num_19_fu_1968_p3);

assign ddr_write_apply_3_num_21_fu_1984_p3 = ((sel_tmp11_fu_1904_p2[0:0] === 1'b1) ? ddr_write_apply_3_num_11_fu_1822_p3 : ddr_write_apply_3_num_20_fu_1976_p3);

assign ddr_write_apply_3_num_22_fu_1992_p3 = ((sel_tmp9_fu_1878_p2[0:0] === 1'b1) ? ddr_write_apply_0_num_2_cast_fu_1965_p1 : ddr_write_apply_3_num_14_fu_1846_p3);

assign ddr_write_apply_3_num_23_fu_2000_p3 = ((sel_tmp10_fu_1891_p2[0:0] === 1'b1) ? ddr_write_apply_3_num_14_fu_1846_p3 : ddr_write_apply_3_num_22_fu_1992_p3);

assign ddr_write_apply_3_num_24_fu_2008_p3 = ((sel_tmp11_fu_1904_p2[0:0] === 1'b1) ? ddr_write_apply_3_num_14_fu_1846_p3 : ddr_write_apply_3_num_23_fu_2000_p3);

assign ddr_write_apply_3_num_25_fu_2016_p3 = ((sel_tmp10_fu_1891_p2[0:0] === 1'b1) ? ddr_write_apply_0_num_2_cast_fu_1965_p1 : ddr_write_apply_3_num_16_fu_1862_p3);

assign ddr_write_apply_3_num_26_fu_2024_p3 = ((sel_tmp11_fu_1904_p2[0:0] === 1'b1) ? ddr_write_apply_3_num_16_fu_1862_p3 : ddr_write_apply_3_num_25_fu_2016_p3);

assign ddr_write_apply_3_num_27_fu_2032_p3 = ((sel_tmp11_fu_1904_p2[0:0] === 1'b1) ? ddr_write_apply_0_num_2_cast_fu_1965_p1 : ddr_write_apply_3_num_17_fu_1870_p3);

assign ddr_write_apply_3_num_3_fu_2121_p3 = ((sel_tmp7_fu_1700_p2[0:0] === 1'b1) ? tmp_num_7_reg_2578 : ddr_write_apply_3_num_2_fu_544);

assign ddr_write_apply_3_num_4_fu_2128_p3 = ((sel_tmp8_fu_1713_p2[0:0] === 1'b1) ? ddr_write_apply_3_num_2_fu_544 : ddr_write_apply_3_num_3_fu_2121_p3);

assign ddr_write_apply_3_num_6_fu_2136_p3 = ((sel_tmp8_fu_1713_p2[0:0] === 1'b1) ? tmp_num_7_reg_2578 : ddr_write_apply_3_num_5_fu_540);

assign ddr_write_apply_3_num_8_fu_1806_p3 = ((sel_tmp6_fu_1687_p2[0:0] === 1'b1) ? tmp_num_3_fu_552 : ddr_write_apply_0_num_fu_1802_p1);

assign ddr_write_apply_3_num_9_fu_1814_p3 = ((sel_tmp7_fu_1700_p2[0:0] === 1'b1) ? tmp_num_3_fu_552 : ddr_write_apply_3_num_8_fu_1806_p3);

assign ddr_write_apply_3_num_fu_2098_p3 = ((or_cond2_fu_2085_p2[0:0] === 1'b1) ? tmp_num_3_fu_552 : newSel4_fu_2091_p3);

assign empty_n_1_nbread_fu_580_p3_0 = (host_dram_write_req_apply_delayed_V_num_empty_n & host_dram_write_req_apply_delayed_V_addr_empty_n);

assign empty_n_4_fu_733_p1 = empty_n_nbread_fu_572_p3_0;

assign empty_n_5_fu_870_p1 = empty_n_1_nbread_fu_580_p3_0;

assign empty_n_nbread_fu_572_p3_0 = (host_dram_read_req_delayed_V_num_empty_n & host_dram_read_req_delayed_V_addr_empty_n);

assign end_addr_V_1_fu_936_p2 = ($signed(tmp_15_fu_918_p1) + $signed(tmp242_cast_fu_932_p1));

assign end_addr_V_fu_799_p2 = ($signed(tmp_8_fu_781_p1) + $signed(tmp241_cast_fu_795_p1));

assign has_read_req_0_not_fu_1562_p2 = (ap_phi_precharge_reg_pp0_iter1_has_read_req1_reg_705 ^ 1'd1);

assign has_write_req_0_not_fu_2207_p2 = (ap_phi_precharge_reg_pp0_iter1_has_write_req1_reg_719 ^ 1'd1);

assign host_dramA_read_req_V_addr_din = ddr_read_req_3_addr_9_fu_524;

assign host_dramA_read_req_V_addr_write = host_dramA_read_req_V_num1_update;

assign host_dramA_read_req_V_num1_status = (host_dramA_read_req_V_num_full_n & host_dramA_read_req_V_addr_full_n);

assign host_dramA_read_req_V_num_din = ddr_read_req_3_num_5_fu_508;

assign host_dramA_read_req_V_num_write = host_dramA_read_req_V_num1_update;

assign host_dramA_write_req_apply_V_addr_din = ddr_write_apply_3_addr_9_fu_556;

assign host_dramA_write_req_apply_V_addr_write = host_dramA_write_req_apply_V_num1_update;

assign host_dramA_write_req_apply_V_num1_status = (host_dramA_write_req_apply_V_num_full_n & host_dramA_write_req_apply_V_addr_full_n);

assign host_dramA_write_req_apply_V_num_din = ddr_write_apply_3_num_5_fu_540;

assign host_dramA_write_req_apply_V_num_write = host_dramA_write_req_apply_V_num1_update;

assign host_dramB_read_req_V_addr_din = ddr_read_req_3_addr_6_fu_528;

assign host_dramB_read_req_V_addr_write = host_dramB_read_req_V_num1_update;

assign host_dramB_read_req_V_num1_status = (host_dramB_read_req_V_num_full_n & host_dramB_read_req_V_addr_full_n);

assign host_dramB_read_req_V_num_din = ddr_read_req_3_num_2_fu_512;

assign host_dramB_read_req_V_num_write = host_dramB_read_req_V_num1_update;

assign host_dramB_write_req_apply_V_addr_din = ddr_write_apply_3_addr_6_fu_560;

assign host_dramB_write_req_apply_V_addr_write = host_dramB_write_req_apply_V_num1_update;

assign host_dramB_write_req_apply_V_num1_status = (host_dramB_write_req_apply_V_num_full_n & host_dramB_write_req_apply_V_addr_full_n);

assign host_dramB_write_req_apply_V_num_din = ddr_write_apply_3_num_2_fu_544;

assign host_dramB_write_req_apply_V_num_write = host_dramB_write_req_apply_V_num1_update;

assign host_dramC_read_req_V_addr_din = tmp_addr_fu_532;

assign host_dramC_read_req_V_addr_write = host_dramC_read_req_V_num1_update;

assign host_dramC_read_req_V_num1_status = (host_dramC_read_req_V_num_full_n & host_dramC_read_req_V_addr_full_n);

assign host_dramC_read_req_V_num_din = tmp_num_fu_516;

assign host_dramC_read_req_V_num_write = host_dramC_read_req_V_num1_update;

assign host_dramC_write_req_apply_V_addr_din = tmp_addr_2_fu_564;

assign host_dramC_write_req_apply_V_addr_write = host_dramC_write_req_apply_V_num1_update;

assign host_dramC_write_req_apply_V_num1_status = (host_dramC_write_req_apply_V_num_full_n & host_dramC_write_req_apply_V_addr_full_n);

assign host_dramC_write_req_apply_V_num_din = tmp_num_2_fu_548;

assign host_dramC_write_req_apply_V_num_write = host_dramC_write_req_apply_V_num1_update;

assign host_dramD_read_req_V_addr_din = tmp_addr_1_fu_536;

assign host_dramD_read_req_V_addr_write = host_dramD_read_req_V_num1_update;

assign host_dramD_read_req_V_num1_status = (host_dramD_read_req_V_num_full_n & host_dramD_read_req_V_addr_full_n);

assign host_dramD_read_req_V_num_din = tmp_num_1_fu_520;

assign host_dramD_read_req_V_num_write = host_dramD_read_req_V_num1_update;

assign host_dramD_write_req_apply_V_addr_din = tmp_addr_3_fu_568;

assign host_dramD_write_req_apply_V_addr_write = host_dramD_write_req_apply_V_num1_update;

assign host_dramD_write_req_apply_V_num1_status = (host_dramD_write_req_apply_V_num_full_n & host_dramD_write_req_apply_V_addr_full_n);

assign host_dramD_write_req_apply_V_num_din = tmp_num_3_fu_552;

assign host_dramD_write_req_apply_V_num_write = host_dramD_write_req_apply_V_num1_update;

assign host_dram_dispatcher_read_context_V_bank_id1_status = (host_dram_dispatcher_read_context_V_bank_id_full_n & host_dram_dispatcher_read_context_V_end_bank_id_full_n & host_dram_dispatcher_read_context_V_cmd_num_full_n);

assign host_dram_dispatcher_read_context_V_bank_id_din = tmp_bank_id_7_reg_2536;

assign host_dram_dispatcher_read_context_V_bank_id_write = host_dram_dispatcher_read_context_V_bank_id1_update;

assign host_dram_dispatcher_read_context_V_cmd_num_din = tmp_num_6_reg_2514;

assign host_dram_dispatcher_read_context_V_cmd_num_write = host_dram_dispatcher_read_context_V_bank_id1_update;

assign host_dram_dispatcher_read_context_V_end_bank_id_write = host_dram_dispatcher_read_context_V_bank_id1_update;

assign host_dram_dispatcher_write_context_V_bank_id1_status = (host_dram_dispatcher_write_context_V_bank_id_full_n & host_dram_dispatcher_write_context_V_end_bank_id_full_n & host_dram_dispatcher_write_context_V_before_boundry_num_full_n & host_dram_dispatcher_write_context_V_cmd_num_full_n);

assign host_dram_dispatcher_write_context_V_bank_id_din = tmp_bank_id_11_reg_2600;

assign host_dram_dispatcher_write_context_V_bank_id_write = host_dram_dispatcher_write_context_V_bank_id1_update;

assign host_dram_dispatcher_write_context_V_before_boundry_num_write = host_dram_dispatcher_write_context_V_bank_id1_update;

assign host_dram_dispatcher_write_context_V_cmd_num_din = tmp_num_7_reg_2578;

assign host_dram_dispatcher_write_context_V_cmd_num_write = host_dram_dispatcher_write_context_V_bank_id1_update;

assign host_dram_dispatcher_write_context_V_end_bank_id_write = host_dram_dispatcher_write_context_V_bank_id1_update;

assign host_dram_read_req_delayed_V_addr_read = host_dram_read_req_delayed_V_num0_update;

assign host_dram_read_req_delayed_V_num_read = host_dram_read_req_delayed_V_num0_update;

assign host_dram_write_req_apply_delayed_V_addr_read = host_dram_write_req_apply_delayed_V_num0_update;

assign host_dram_write_req_apply_delayed_V_num_read = host_dram_write_req_apply_delayed_V_num0_update;

assign host_dram_write_resp_V_din = 1'd0;

assign lhs_V_2_cast_fu_977_p1 = end_addr_V_1_fu_936_p2;

assign lhs_V_cast_fu_840_p1 = end_addr_V_fu_799_p2;

assign newSel2_fu_1461_p3 = ((sel_tmp_fu_1047_p2[0:0] === 1'b1) ? tmp_num_6_reg_2514 : tmp_num_fu_516);

assign newSel4_fu_2091_p3 = ((sel_tmp6_fu_1687_p2[0:0] === 1'b1) ? tmp_num_3_fu_552 : tmp_num_7_reg_2578);

assign newSel6_fu_2106_p3 = ((sel_tmp6_fu_1687_p2[0:0] === 1'b1) ? tmp_num_7_reg_2578 : tmp_num_2_fu_548);

assign newSel_fu_1446_p3 = ((sel_tmp_fu_1047_p2[0:0] === 1'b1) ? tmp_num_1_fu_520 : tmp_num_6_reg_2514);

assign notlhs1_fu_1574_p2 = ((tmp_bank_id_3_fu_504 != 8'd1) ? 1'b1 : 1'b0);

assign notlhs2_fu_1598_p2 = ((tmp_bank_id_3_fu_504 != 8'd2) ? 1'b1 : 1'b0);

assign notlhs3_fu_1622_p2 = ((tmp_bank_id_3_fu_504 != 8'd3) ? 1'b1 : 1'b0);

assign notlhs4_fu_2189_p2 = ((tmp_bank_id_1_fu_496 != 8'd0) ? 1'b1 : 1'b0);

assign notlhs5_fu_2219_p2 = ((tmp_bank_id_1_fu_496 != 8'd1) ? 1'b1 : 1'b0);

assign notlhs6_fu_2243_p2 = ((tmp_bank_id_1_fu_496 != 8'd2) ? 1'b1 : 1'b0);

assign notlhs7_fu_2267_p2 = ((tmp_bank_id_1_fu_496 != 8'd3) ? 1'b1 : 1'b0);

assign notlhs_fu_1544_p2 = ((tmp_bank_id_3_fu_504 != 8'd0) ? 1'b1 : 1'b0);

assign notrhs1_fu_1580_p2 = ((tmp_bank_id_2_fu_500 != 8'd1) ? 1'b1 : 1'b0);

assign notrhs2_fu_1604_p2 = ((tmp_bank_id_2_fu_500 != 8'd2) ? 1'b1 : 1'b0);

assign notrhs3_fu_1628_p2 = ((tmp_bank_id_2_fu_500 != 8'd3) ? 1'b1 : 1'b0);

assign notrhs4_fu_2195_p2 = ((tmp_bank_id_fu_492 != 8'd0) ? 1'b1 : 1'b0);

assign notrhs5_fu_2225_p2 = ((tmp_bank_id_fu_492 != 8'd1) ? 1'b1 : 1'b0);

assign notrhs6_fu_2249_p2 = ((tmp_bank_id_fu_492 != 8'd2) ? 1'b1 : 1'b0);

assign notrhs7_fu_2273_p2 = ((tmp_bank_id_fu_492 != 8'd3) ? 1'b1 : 1'b0);

assign notrhs_fu_1550_p2 = ((tmp_bank_id_2_fu_500 != 8'd0) ? 1'b1 : 1'b0);

assign or_cond288_not_fu_1586_p2 = (notrhs1_fu_1580_p2 & notlhs1_fu_1574_p2);

assign or_cond291_not_fu_1610_p2 = (notrhs2_fu_1604_p2 & notlhs2_fu_1598_p2);

assign or_cond294_not_fu_1634_p2 = (notrhs3_fu_1628_p2 & notlhs3_fu_1622_p2);

assign or_cond297_not_fu_2201_p2 = (notrhs4_fu_2195_p2 & notlhs4_fu_2189_p2);

assign or_cond299_not_fu_2231_p2 = (notrhs5_fu_2225_p2 & notlhs5_fu_2219_p2);

assign or_cond2_fu_2085_p2 = (sel_tmp8_fu_1713_p2 | sel_tmp7_fu_1700_p2);

assign or_cond302_not_fu_2255_p2 = (notrhs6_fu_2249_p2 & notlhs6_fu_2243_p2);

assign or_cond305_not_fu_2279_p2 = (notrhs7_fu_2273_p2 & notlhs7_fu_2267_p2);

assign or_cond_fu_1440_p2 = (sel_tmp4_fu_1073_p2 | sel_tmp2_fu_1060_p2);

assign or_cond_not_fu_1556_p2 = (notrhs_fu_1550_p2 & notlhs_fu_1544_p2);

assign r_V_1_fu_981_p2 = (lhs_V_2_cast_fu_977_p1 + 37'd1);

assign r_V_fu_844_p2 = (lhs_V_cast_fu_840_p1 + 37'd1);

assign read_bank_id_fu_749_p4 = {{host_dram_read_req_delayed_V_addr_dout[13:12]}};

assign read_end_bank_id_fu_805_p4 = {{end_addr_V_fu_799_p2[13:12]}};

assign sel_tmp10_fu_1891_p2 = ((write_end_bank_id_reg_2611 == 2'd1) ? 1'b1 : 1'b0);

assign sel_tmp11_fu_1904_p2 = ((write_end_bank_id_reg_2611 == 2'd0) ? 1'b1 : 1'b0);

assign sel_tmp1_fu_1238_p2 = ((read_end_bank_id_reg_2547 == 2'd2) ? 1'b1 : 1'b0);

assign sel_tmp2_fu_1060_p2 = ((read_bank_id_reg_2529 == 2'd1) ? 1'b1 : 1'b0);

assign sel_tmp3_fu_1251_p2 = ((read_end_bank_id_reg_2547 == 2'd1) ? 1'b1 : 1'b0);

assign sel_tmp4_fu_1073_p2 = ((read_bank_id_reg_2529 == 2'd0) ? 1'b1 : 1'b0);

assign sel_tmp5_fu_1264_p2 = ((read_end_bank_id_reg_2547 == 2'd0) ? 1'b1 : 1'b0);

assign sel_tmp6_fu_1687_p2 = ((write_bank_id_reg_2593 == 2'd2) ? 1'b1 : 1'b0);

assign sel_tmp7_fu_1700_p2 = ((write_bank_id_reg_2593 == 2'd1) ? 1'b1 : 1'b0);

assign sel_tmp8_fu_1713_p2 = ((write_bank_id_reg_2593 == 2'd0) ? 1'b1 : 1'b0);

assign sel_tmp9_fu_1878_p2 = ((write_end_bank_id_reg_2611 == 2'd2) ? 1'b1 : 1'b0);

assign sel_tmp_fu_1047_p2 = ((read_bank_id_reg_2529 == 2'd2) ? 1'b1 : 1'b0);

assign tmp241_cast_fu_795_p1 = $signed(tmp3_fu_789_p2);

assign tmp242_cast_fu_932_p1 = $signed(tmp7_fu_926_p2);

assign tmp3_fu_789_p2 = ($signed(15'd32767) + $signed(tmp_9_cast_fu_785_p1));

assign tmp7_fu_926_p2 = ($signed(15'd32767) + $signed(tmp_23_cast_fu_922_p1));

assign tmp_10_fu_882_p1 = host_dram_write_req_apply_delayed_V_addr_dout[11:0];

assign tmp_12_fu_966_p2 = ((write_bank_id_fu_886_p4 == write_end_bank_id_fu_942_p4) ? 1'b1 : 1'b0);

assign tmp_13_fu_1786_p2 = ($signed(13'd4096) - $signed(tmp_20_cast_fu_1658_p1));

assign tmp_14_fu_1792_p4 = {{tmp_13_fu_1786_p2[12:6]}};

assign tmp_15_fu_918_p1 = host_dram_write_req_apply_delayed_V_addr_dout[35:0];

assign tmp_20_cast_fu_1658_p1 = tmp_10_reg_2587;

assign tmp_23_cast_fu_922_p1 = tmp_9_fu_910_p3;

assign tmp_3_fu_829_p2 = ((read_bank_id_fu_749_p4 == read_end_bank_id_fu_805_p4) ? 1'b1 : 1'b0);

assign tmp_4_fu_1146_p2 = ($signed(13'd4096) - $signed(tmp_5_cast_fu_1019_p1));

assign tmp_5_cast_fu_1019_p1 = tmp_reg_2523;

assign tmp_5_fu_1152_p4 = {{tmp_4_fu_1146_p2[12:6]}};

assign tmp_7_fu_773_p3 = {{host_dram_read_req_delayed_V_num_dout}, {6'd0}};

assign tmp_8_fu_781_p1 = host_dram_read_req_delayed_V_addr_dout[35:0];

assign tmp_9_cast_fu_785_p1 = tmp_7_fu_773_p3;

assign tmp_9_fu_910_p3 = {{host_dram_write_req_apply_delayed_V_num_dout}, {6'd0}};

assign tmp_bank_id_11_fu_896_p1 = write_bank_id_fu_886_p4;

assign tmp_bank_id_7_fu_759_p1 = read_bank_id_fu_749_p4;

assign tmp_before_boundry_num_fu_2040_p1 = tmp_14_fu_1792_p4;

assign tmp_end_bank_id_2_fu_815_p1 = read_end_bank_id_fu_805_p4;

assign tmp_end_bank_id_6_fu_952_p1 = write_end_bank_id_fu_942_p4;

assign tmp_fu_745_p1 = host_dram_read_req_delayed_V_addr_dout[11:0];

assign write_bank_id_fu_886_p4 = {{host_dram_write_req_apply_delayed_V_addr_dout[13:12]}};

assign write_end_bank_id_fu_942_p4 = {{end_addr_V_1_fu_936_p2[13:12]}};

always @ (posedge ap_clk) begin
    tmp_bank_id_7_reg_2536[7:2] <= 6'b000000;
    tmp_end_bank_id_2_reg_2554[7:2] <= 6'b000000;
    tmp_bank_id_11_reg_2600[7:2] <= 6'b000000;
    tmp_end_bank_id_6_reg_2618[7:2] <= 6'b000000;
    tmp_bank_id_fu_492[7:2] <= 6'b000000;
    tmp_bank_id_1_fu_496[7:2] <= 6'b000000;
    tmp_bank_id_2_fu_500[7:2] <= 6'b000000;
    tmp_bank_id_3_fu_504[7:2] <= 6'b000000;
end

endmodule //host_pipe0_dram_dispatcher
