// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pipe2_data_handler,hls_ip_2017_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-2-i,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.741000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=770,HLS_SYN_LUT=682}" *)

module pipe2_data_handler (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
ap_continue,
        ap_idle,
        ap_ready,
        reqs_pipe2_read_V_sector_off_dout,
        reqs_pipe2_read_V_sector_off_empty_n,
        reqs_pipe2_read_V_sector_off_read,
        reqs_pipe2_read_V_sector_num_dout,
        reqs_pipe2_read_V_sector_num_empty_n,
        reqs_pipe2_read_V_sector_num_read,
        reqs_pipe2_read_V_tag_dout,
        reqs_pipe2_read_V_tag_empty_n,
        reqs_pipe2_read_V_tag_read,
        reqs_pipe2_read_V_rw_dout,
        reqs_pipe2_read_V_rw_empty_n,
        reqs_pipe2_read_V_rw_read,
        data_valid_pipe2_read_V_dout,
        data_valid_pipe2_read_V_empty_n,
        data_valid_pipe2_read_V_read,
        kbuf_addr_pipe2_read_V_dout,
        kbuf_addr_pipe2_read_V_empty_n,
        kbuf_addr_pipe2_read_V_read,
        data_pipe2_read_V_last_dout,
        data_pipe2_read_V_last_empty_n,
        data_pipe2_read_V_last_read,
        data_pipe2_read_V_data_V_dout,
        data_pipe2_read_V_data_V_empty_n,
        data_pipe2_read_V_data_V_read,
        host_data_pcie_write_req_apply_V_num_din,
        host_data_pcie_write_req_apply_V_num_full_n,
        host_data_pcie_write_req_apply_V_num_write,
        host_data_pcie_write_req_apply_V_addr_din,
        host_data_pcie_write_req_apply_V_addr_full_n,
        host_data_pcie_write_req_apply_V_addr_write,
        host_fin_pcie_write_req_apply_V_num_din,
        host_fin_pcie_write_req_apply_V_num_full_n,
        host_fin_pcie_write_req_apply_V_num_write,
        host_fin_pcie_write_req_apply_V_addr_din,
        host_fin_pcie_write_req_apply_V_addr_full_n,
        host_fin_pcie_write_req_apply_V_addr_write,
        host_data_pcie_write_req_data_V_last_din,
        host_data_pcie_write_req_data_V_last_full_n,
        host_data_pcie_write_req_data_V_last_write,
        host_data_pcie_write_req_data_V_data_V_din,
        host_data_pcie_write_req_data_V_data_V_full_n,
        host_data_pcie_write_req_data_V_data_V_write,
        host_dram_write_req_apply_V_num_din,
        host_dram_write_req_apply_V_num_full_n,
        host_dram_write_req_apply_V_num_write,
        host_dram_write_req_apply_V_addr_din,
        host_dram_write_req_apply_V_addr_full_n,
        host_dram_write_req_apply_V_addr_write,
        host_dram_write_req_data_V_last_din,
        host_dram_write_req_data_V_last_full_n,
        host_dram_write_req_data_V_last_write,
        host_dram_write_req_data_V_data_V_din,
        host_dram_write_req_data_V_data_V_full_n,
        host_dram_write_req_data_V_data_V_write,
        host_fin_pcie_write_req_data_V_last_din,
        host_fin_pcie_write_req_data_V_last_full_n,
        host_fin_pcie_write_req_data_V_last_write,
        host_fin_pcie_write_req_data_V_data_V_din,
        host_fin_pcie_write_req_data_V_data_V_full_n,
        host_fin_pcie_write_req_data_V_data_V_write,
        host_dram_write_resp_V_dout,
        host_dram_write_resp_V_empty_n,
        host_dram_write_resp_V_read
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output ap_ready; output ap_continue;
input  [31:0] reqs_pipe2_read_V_sector_off_dout;
input   reqs_pipe2_read_V_sector_off_empty_n;
output   reqs_pipe2_read_V_sector_off_read;
input  [31:0] reqs_pipe2_read_V_sector_num_dout;
input   reqs_pipe2_read_V_sector_num_empty_n;
output   reqs_pipe2_read_V_sector_num_read;
input  [31:0] reqs_pipe2_read_V_tag_dout;
input   reqs_pipe2_read_V_tag_empty_n;
output   reqs_pipe2_read_V_tag_read;
input   reqs_pipe2_read_V_rw_dout;
input   reqs_pipe2_read_V_rw_empty_n;
output   reqs_pipe2_read_V_rw_read;
input   data_valid_pipe2_read_V_dout;
input   data_valid_pipe2_read_V_empty_n;
output   data_valid_pipe2_read_V_read;
input  [63:0] kbuf_addr_pipe2_read_V_dout;
input   kbuf_addr_pipe2_read_V_empty_n;
output   kbuf_addr_pipe2_read_V_read;
input   data_pipe2_read_V_last_dout;
input   data_pipe2_read_V_last_empty_n;
output   data_pipe2_read_V_last_read;
input  [511:0] data_pipe2_read_V_data_V_dout;
input   data_pipe2_read_V_data_V_empty_n;
output   data_pipe2_read_V_data_V_read;
output  [7:0] host_data_pcie_write_req_apply_V_num_din;
input   host_data_pcie_write_req_apply_V_num_full_n;
output   host_data_pcie_write_req_apply_V_num_write;
output  [63:0] host_data_pcie_write_req_apply_V_addr_din;
input   host_data_pcie_write_req_apply_V_addr_full_n;
output   host_data_pcie_write_req_apply_V_addr_write;
output  [7:0] host_fin_pcie_write_req_apply_V_num_din;
input   host_fin_pcie_write_req_apply_V_num_full_n;
output   host_fin_pcie_write_req_apply_V_num_write;
output  [63:0] host_fin_pcie_write_req_apply_V_addr_din;
input   host_fin_pcie_write_req_apply_V_addr_full_n;
output   host_fin_pcie_write_req_apply_V_addr_write;
output   host_data_pcie_write_req_data_V_last_din;
input   host_data_pcie_write_req_data_V_last_full_n;
output   host_data_pcie_write_req_data_V_last_write;
output  [511:0] host_data_pcie_write_req_data_V_data_V_din;
input   host_data_pcie_write_req_data_V_data_V_full_n;
output   host_data_pcie_write_req_data_V_data_V_write;
output  [7:0] host_dram_write_req_apply_V_num_din;
input   host_dram_write_req_apply_V_num_full_n;
output   host_dram_write_req_apply_V_num_write;
output  [63:0] host_dram_write_req_apply_V_addr_din;
input   host_dram_write_req_apply_V_addr_full_n;
output   host_dram_write_req_apply_V_addr_write;
output   host_dram_write_req_data_V_last_din;
input   host_dram_write_req_data_V_last_full_n;
output   host_dram_write_req_data_V_last_write;
output  [511:0] host_dram_write_req_data_V_data_V_din;
input   host_dram_write_req_data_V_data_V_full_n;
output   host_dram_write_req_data_V_data_V_write;
output   host_fin_pcie_write_req_data_V_last_din;
input   host_fin_pcie_write_req_data_V_last_full_n;
output   host_fin_pcie_write_req_data_V_last_write;
output  [511:0] host_fin_pcie_write_req_data_V_data_V_din;
input   host_fin_pcie_write_req_data_V_data_V_full_n;
output   host_fin_pcie_write_req_data_V_data_V_write;
input   host_dram_write_resp_V_dout;
input   host_dram_write_resp_V_empty_n;
output   host_dram_write_resp_V_read;

reg ap_idle;
reg data_valid_pipe2_read_V_read;
reg kbuf_addr_pipe2_read_V_read;
reg[63:0] host_fin_pcie_write_req_apply_V_addr_din;
reg host_dram_write_resp_V_read;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    host_data_pcie_write_req_apply_V_num_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] brmerge82_demorgan_reg_953;
reg   [0:0] tmp_rw_load_reg_957;
reg   [0:0] empty_n_7_reg_961;
reg   [0:0] p_first_reg_945;
reg    host_data_pcie_write_req_apply_V_addr_blk_n;
reg    host_fin_pcie_write_req_apply_V_num_blk_n;
reg   [0:0] tmp_last_2_reg_965;
reg   [0:0] p_is_write_last_reg_949;
reg   [0:0] empty_n_8_reg_994;
reg    host_fin_pcie_write_req_apply_V_addr_blk_n;
reg    host_data_pcie_write_req_data_V_last_blk_n;
reg    host_data_pcie_write_req_data_V_data_V_blk_n;
reg    host_dram_write_req_apply_V_num_blk_n;
reg    host_dram_write_req_apply_V_addr_blk_n;
reg    host_dram_write_req_data_V_last_blk_n;
reg   [0:0] empty_n_9_reg_985;
reg    host_dram_write_req_data_V_data_V_blk_n;
reg    host_fin_pcie_write_req_data_V_last_blk_n;
reg    host_fin_pcie_write_req_data_V_data_V_blk_n;
reg   [0:0] reset_reg_493;
reg   [511:0] reg_585;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    host_data_pcie_write_req_apply_V_num1_status;
reg    ap_predicate_op173_write_state4;
wire    host_data_pcie_write_req_data_V_last1_status;
reg    ap_predicate_op175_write_state4;
wire    host_fin_pcie_write_req_apply_V_num1_status;
reg    ap_predicate_op179_write_state4;
wire    host_fin_pcie_write_req_data_V_last1_status;
wire    host_dram_write_req_apply_V_num1_status;
reg    ap_predicate_op184_write_state4;
wire    host_dram_write_req_data_V_last1_status;
reg    ap_predicate_op186_write_state4;
reg    ap_predicate_op189_write_state4;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] brmerge82_demorgan_fu_773_p2;
wire   [0:0] tmp_rw_load_load_fu_779_p1;
wire   [0:0] p_is_write_last_fu_748_p2;
wire   [0:0] not_reset_fu_620_p2;
reg   [0:0] not_reset_reg_921;
wire   [0:0] p_has_kbu_fu_640_p2;
reg   [0:0] p_has_kbu_reg_932;
wire   [0:0] brmerge1_fu_671_p2;
reg   [0:0] brmerge1_reg_936;
reg   [63:0] tmp_2_reg_940;
wire   [0:0] p_first_fu_741_p2;
wire   [0:0] grp_fu_561_p1;
wire   [0:0] grp_fu_565_p1;
wire   [4:0] tmp_1_fu_782_p1;
reg   [4:0] tmp_1_reg_970;
reg   [31:0] tmp_sector_off_load_reg_975;
wire   [4:0] tmp_fu_789_p1;
reg   [4:0] tmp_reg_980;
reg   [0:0] tmp_last_3_reg_989;
wire   [0:0] empty_n_8_fu_798_p1;
reg    ap_enable_reg_pp0_iter0;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] reset_phi_fu_497_p4;
reg   [0:0] reset_8_phi_fu_509_p16;
wire   [0:0] ap_phi_precharge_reg_pp0_iter1_reset_8_reg_505;
reg    reqs_pipe2_read_V_rw0_update;
wire   [0:0] p_has_reqs_fu_626_p2;
reg    ap_condition_333;
wire   [0:0] empty_n_6_nbread_fu_392_p5_0;
wire   [0:0] p_has_data_valid_fu_633_p2;
reg    data_pipe2_read_V_last0_update;
wire   [0:0] grp_nbread_fu_416_p3_0;
reg    host_data_pcie_write_req_apply_V_num1_update;
reg    ap_block_pp0_stage0_01001;
reg    host_data_pcie_write_req_data_V_last1_update;
reg    host_fin_pcie_write_req_apply_V_num1_update;
wire   [63:0] fin_write_apply_addr_fu_818_p2;
wire   [63:0] fin_write_apply_addr_2_fu_845_p2;
reg    host_fin_pcie_write_req_data_V_last1_update;
reg    host_dram_write_req_apply_V_num1_update;
reg    host_dram_write_req_data_V_last1_update;
reg   [0:0] tmp_last_fu_356;
reg   [0:0] has_kbuf_addr_fu_360;
reg   [0:0] has_data_valid_fu_364;
reg   [0:0] has_reqs_fu_368;
reg   [0:0] first_fu_372;
reg   [63:0] tmp_addr_fu_376;
reg   [0:0] tmp_rw_fu_380;
reg   [31:0] tmp_sector_num_fu_384;
reg   [31:0] tmp_sector_off_fu_388;
wire   [0:0] has_reqs_0_not_fu_647_p2;
wire   [0:0] tmp2_demorgan_fu_659_p2;
wire   [0:0] tmp1_fu_653_p2;
wire   [0:0] tmp2_fu_665_p2;
wire   [0:0] tmp3_fu_767_p2;
wire   [40:0] write_apply_addr_fu_825_p3;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_subdone == 1'b0)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_subdone == 1'b0)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd0 == tmp_rw_load_load_fu_779_p1) & (1'd1 == grp_fu_561_p1) & (1'd1 == p_first_fu_741_p2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd1 == tmp_rw_load_load_fu_779_p1) & (1'd1 == p_first_fu_741_p2)))) begin
        first_fu_372 <= 1'd0;
    end else if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd0 == tmp_rw_load_load_fu_779_p1) & (1'd0 == grp_fu_561_p1)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd0 == brmerge82_demorgan_fu_773_p2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd0 == tmp_rw_load_load_fu_779_p1) & (1'd1 == grp_fu_561_p1) & (1'd0 == p_first_fu_741_p2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd1 == tmp_rw_load_load_fu_779_p1) & (1'd0 == p_first_fu_741_p2)))) begin
        first_fu_372 <= p_first_fu_741_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        first_fu_372 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge1_fu_671_p2) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == p_has_data_valid_fu_633_p2))) begin
        has_data_valid_fu_364 <= data_valid_pipe2_read_V_empty_n;
    end else if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == brmerge1_fu_671_p2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge1_fu_671_p2) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd1 == p_has_data_valid_fu_633_p2)))) begin
        has_data_valid_fu_364 <= p_has_data_valid_fu_633_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        has_data_valid_fu_364 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge1_fu_671_p2) & (1'd0 == p_has_kbu_fu_640_p2) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        has_kbuf_addr_fu_360 <= kbuf_addr_pipe2_read_V_empty_n;
    end else if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == brmerge1_fu_671_p2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge1_fu_671_p2) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd1 == p_has_kbu_fu_640_p2)))) begin
        has_kbuf_addr_fu_360 <= p_has_kbu_fu_640_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        has_kbuf_addr_fu_360 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge1_fu_671_p2) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == p_has_reqs_fu_626_p2))) begin
        has_reqs_fu_368 <= empty_n_6_nbread_fu_392_p5_0;
    end else if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == brmerge1_fu_671_p2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge1_fu_671_p2) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd1 == p_has_reqs_fu_626_p2)))) begin
        has_reqs_fu_368 <= p_has_reqs_fu_626_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        has_reqs_fu_368 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        reset_reg_493 <= reset_8_phi_fu_509_p16;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reset_reg_493 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd1 == tmp_rw_load_load_fu_779_p1) & (1'd1 == p_is_write_last_fu_748_p2))) begin
        tmp_last_fu_356 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd1 == tmp_rw_load_load_fu_779_p1) & (1'd0 == p_is_write_last_fu_748_p2) & (1'd1 == grp_fu_561_p1))) begin
        tmp_last_fu_356 <= data_pipe2_read_V_last_dout;
    end else if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd0 == tmp_rw_load_load_fu_779_p1) & (1'd1 == grp_fu_561_p1) & (1'd1 == grp_fu_565_p1)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd0 == tmp_rw_load_load_fu_779_p1) & (1'd1 == grp_fu_561_p1) & (1'd0 == grp_fu_565_p1)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd0 == tmp_rw_load_load_fu_779_p1) & (1'd0 == grp_fu_561_p1)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd0 == brmerge82_demorgan_fu_773_p2)))) begin
        tmp_last_fu_356 <= p_is_write_last_fu_748_p2;
    end else if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd1 == tmp_rw_load_load_fu_779_p1) & (1'd0 == p_is_write_last_fu_748_p2) & (1'd0 == grp_fu_561_p1)))) begin
        tmp_last_fu_356 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        brmerge1_reg_936 <= brmerge1_fu_671_p2;
        brmerge82_demorgan_reg_953 <= brmerge82_demorgan_fu_773_p2;
        not_reset_reg_921 <= not_reset_fu_620_p2;
        p_first_reg_945 <= p_first_fu_741_p2;
        p_has_kbu_reg_932 <= p_has_kbu_fu_640_p2;
        p_is_write_last_reg_949 <= p_is_write_last_fu_748_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd0 == tmp_rw_load_load_fu_779_p1))) begin
        empty_n_7_reg_961 <= grp_nbread_fu_416_p3_0;
        tmp_last_2_reg_965 <= data_pipe2_read_V_last_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd1 == tmp_rw_load_load_fu_779_p1) & (1'd1 == p_is_write_last_fu_748_p2))) begin
        empty_n_8_reg_994 <= host_dram_write_resp_V_empty_n;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd1 == tmp_rw_load_load_fu_779_p1) & (1'd0 == p_is_write_last_fu_748_p2))) begin
        empty_n_9_reg_985 <= grp_nbread_fu_416_p3_0;
        tmp_last_3_reg_989 <= data_pipe2_read_V_last_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd0 == tmp_rw_load_load_fu_779_p1)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd1 == tmp_rw_load_load_fu_779_p1) & (1'd0 == p_is_write_last_fu_748_p2)))) begin
        reg_585 <= data_pipe2_read_V_data_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd0 == tmp_rw_load_load_fu_779_p1) & (1'd1 == grp_fu_561_p1) & (1'd1 == p_first_fu_741_p2))) begin
        tmp_1_reg_970 <= tmp_1_fu_782_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge1_fu_671_p2) & (1'd0 == p_has_kbu_fu_640_p2))) begin
        tmp_2_reg_940 <= kbuf_addr_pipe2_read_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge1_reg_936) & (1'd0 == p_has_kbu_reg_932))) begin
        tmp_addr_fu_376 <= tmp_2_reg_940;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd1 == tmp_rw_load_load_fu_779_p1) & (1'd1 == p_first_fu_741_p2))) begin
        tmp_reg_980 <= tmp_fu_789_p1;
        tmp_sector_off_load_reg_975 <= tmp_sector_off_fu_388;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge1_fu_671_p2) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == p_has_reqs_fu_626_p2))) begin
        tmp_rw_fu_380 <= reqs_pipe2_read_V_rw_dout;
        tmp_sector_num_fu_384 <= reqs_pipe2_read_V_sector_num_dout;
        tmp_sector_off_fu_388 <= reqs_pipe2_read_V_sector_off_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2))) begin
        tmp_rw_load_reg_957 <= tmp_rw_fu_380;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1) & (1'b0 == ap_enable_reg_pp0_iter2))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd0 == tmp_rw_load_load_fu_779_p1)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd1 == tmp_rw_load_load_fu_779_p1) & (1'd0 == p_is_write_last_fu_748_p2))) & (1'b1 == (data_pipe2_read_V_last_empty_n & data_pipe2_read_V_data_V_empty_n)))) begin
        data_pipe2_read_V_last0_update = 1'b1;
    end else begin
        data_pipe2_read_V_last0_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge1_fu_671_p2) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == p_has_data_valid_fu_633_p2) & (1'b1 == data_valid_pipe2_read_V_empty_n))) begin
        data_valid_pipe2_read_V_read = 1'b1;
    end else begin
        data_valid_pipe2_read_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (brmerge82_demorgan_reg_953 == 1'd1) & (tmp_rw_load_reg_957 == 1'd0) & (1'd1 == empty_n_7_reg_961) & (1'd1 == p_first_reg_945))) begin
        host_data_pcie_write_req_apply_V_addr_blk_n = host_data_pcie_write_req_apply_V_addr_full_n;
    end else begin
        host_data_pcie_write_req_apply_V_addr_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_predicate_op173_write_state4) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        host_data_pcie_write_req_apply_V_num1_update = 1'b1;
    end else begin
        host_data_pcie_write_req_apply_V_num1_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (brmerge82_demorgan_reg_953 == 1'd1) & (tmp_rw_load_reg_957 == 1'd0) & (1'd1 == empty_n_7_reg_961) & (1'd1 == p_first_reg_945))) begin
        host_data_pcie_write_req_apply_V_num_blk_n = host_data_pcie_write_req_apply_V_num_full_n;
    end else begin
        host_data_pcie_write_req_apply_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (brmerge82_demorgan_reg_953 == 1'd1) & (tmp_rw_load_reg_957 == 1'd0) & (1'd1 == empty_n_7_reg_961))) begin
        host_data_pcie_write_req_data_V_data_V_blk_n = host_data_pcie_write_req_data_V_data_V_full_n;
    end else begin
        host_data_pcie_write_req_data_V_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_predicate_op175_write_state4) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        host_data_pcie_write_req_data_V_last1_update = 1'b1;
    end else begin
        host_data_pcie_write_req_data_V_last1_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (brmerge82_demorgan_reg_953 == 1'd1) & (tmp_rw_load_reg_957 == 1'd0) & (1'd1 == empty_n_7_reg_961))) begin
        host_data_pcie_write_req_data_V_last_blk_n = host_data_pcie_write_req_data_V_last_full_n;
    end else begin
        host_data_pcie_write_req_data_V_last_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (brmerge82_demorgan_reg_953 == 1'd1) & (1'd1 == p_first_reg_945) & (1'd1 == tmp_rw_load_reg_957))) begin
        host_dram_write_req_apply_V_addr_blk_n = host_dram_write_req_apply_V_addr_full_n;
    end else begin
        host_dram_write_req_apply_V_addr_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_predicate_op184_write_state4) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        host_dram_write_req_apply_V_num1_update = 1'b1;
    end else begin
        host_dram_write_req_apply_V_num1_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (brmerge82_demorgan_reg_953 == 1'd1) & (1'd1 == p_first_reg_945) & (1'd1 == tmp_rw_load_reg_957))) begin
        host_dram_write_req_apply_V_num_blk_n = host_dram_write_req_apply_V_num_full_n;
    end else begin
        host_dram_write_req_apply_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (brmerge82_demorgan_reg_953 == 1'd1) & (1'd1 == tmp_rw_load_reg_957) & (1'd0 == p_is_write_last_reg_949) & (1'd1 == empty_n_9_reg_985))) begin
        host_dram_write_req_data_V_data_V_blk_n = host_dram_write_req_data_V_data_V_full_n;
    end else begin
        host_dram_write_req_data_V_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_predicate_op186_write_state4) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        host_dram_write_req_data_V_last1_update = 1'b1;
    end else begin
        host_dram_write_req_data_V_last1_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (brmerge82_demorgan_reg_953 == 1'd1) & (1'd1 == tmp_rw_load_reg_957) & (1'd0 == p_is_write_last_reg_949) & (1'd1 == empty_n_9_reg_985))) begin
        host_dram_write_req_data_V_last_blk_n = host_dram_write_req_data_V_last_full_n;
    end else begin
        host_dram_write_req_data_V_last_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd1 == tmp_rw_load_load_fu_779_p1) & (1'd1 == p_is_write_last_fu_748_p2) & (1'b1 == host_dram_write_resp_V_empty_n))) begin
        host_dram_write_resp_V_read = 1'b1;
    end else begin
        host_dram_write_resp_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (brmerge82_demorgan_reg_953 == 1'd1) & (tmp_rw_load_reg_957 == 1'd0) & (1'd1 == empty_n_7_reg_961) & (1'd1 == tmp_last_2_reg_965)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (brmerge82_demorgan_reg_953 == 1'd1) & (1'd1 == tmp_rw_load_reg_957) & (1'd1 == p_is_write_last_reg_949) & (1'd1 == empty_n_8_reg_994)))) begin
        host_fin_pcie_write_req_apply_V_addr_blk_n = host_fin_pcie_write_req_apply_V_addr_full_n;
    end else begin
        host_fin_pcie_write_req_apply_V_addr_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0_01001 == 1'b0))) begin
        if ((1'b1 == ap_predicate_op189_write_state4)) begin
            host_fin_pcie_write_req_apply_V_addr_din = fin_write_apply_addr_2_fu_845_p2;
        end else if ((1'b1 == ap_predicate_op179_write_state4)) begin
            host_fin_pcie_write_req_apply_V_addr_din = fin_write_apply_addr_fu_818_p2;
        end else begin
            host_fin_pcie_write_req_apply_V_addr_din = 'bx;
        end
    end else begin
        host_fin_pcie_write_req_apply_V_addr_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_predicate_op179_write_state4) & (ap_block_pp0_stage0_11001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_predicate_op189_write_state4) & (ap_block_pp0_stage0_11001 == 1'b0)))) begin
        host_fin_pcie_write_req_apply_V_num1_update = 1'b1;
    end else begin
        host_fin_pcie_write_req_apply_V_num1_update = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (brmerge82_demorgan_reg_953 == 1'd1) & (tmp_rw_load_reg_957 == 1'd0) & (1'd1 == empty_n_7_reg_961) & (1'd1 == tmp_last_2_reg_965)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (brmerge82_demorgan_reg_953 == 1'd1) & (1'd1 == tmp_rw_load_reg_957) & (1'd1 == p_is_write_last_reg_949) & (1'd1 == empty_n_8_reg_994)))) begin
        host_fin_pcie_write_req_apply_V_num_blk_n = host_fin_pcie_write_req_apply_V_num_full_n;
    end else begin
        host_fin_pcie_write_req_apply_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (brmerge82_demorgan_reg_953 == 1'd1) & (tmp_rw_load_reg_957 == 1'd0) & (1'd1 == empty_n_7_reg_961) & (1'd1 == tmp_last_2_reg_965)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (brmerge82_demorgan_reg_953 == 1'd1) & (1'd1 == tmp_rw_load_reg_957) & (1'd1 == p_is_write_last_reg_949) & (1'd1 == empty_n_8_reg_994)))) begin
        host_fin_pcie_write_req_data_V_data_V_blk_n = host_fin_pcie_write_req_data_V_data_V_full_n;
    end else begin
        host_fin_pcie_write_req_data_V_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_predicate_op179_write_state4) & (ap_block_pp0_stage0_11001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_predicate_op189_write_state4) & (ap_block_pp0_stage0_11001 == 1'b0)))) begin
        host_fin_pcie_write_req_data_V_last1_update = 1'b1;
    end else begin
        host_fin_pcie_write_req_data_V_last1_update = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (brmerge82_demorgan_reg_953 == 1'd1) & (tmp_rw_load_reg_957 == 1'd0) & (1'd1 == empty_n_7_reg_961) & (1'd1 == tmp_last_2_reg_965)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0 == 1'b0) & (brmerge82_demorgan_reg_953 == 1'd1) & (1'd1 == tmp_rw_load_reg_957) & (1'd1 == p_is_write_last_reg_949) & (1'd1 == empty_n_8_reg_994)))) begin
        host_fin_pcie_write_req_data_V_last_blk_n = host_fin_pcie_write_req_data_V_last_full_n;
    end else begin
        host_fin_pcie_write_req_data_V_last_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge1_fu_671_p2) & (1'd0 == p_has_kbu_fu_640_p2) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == kbuf_addr_pipe2_read_V_empty_n))) begin
        kbuf_addr_pipe2_read_V_read = 1'b1;
    end else begin
        kbuf_addr_pipe2_read_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd1 == brmerge1_fu_671_p2) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == p_has_reqs_fu_626_p2) & (ap_condition_333 == 1'b1))) begin
        reqs_pipe2_read_V_rw0_update = 1'b1;
    end else begin
        reqs_pipe2_read_V_rw0_update = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd1 == tmp_rw_load_load_fu_779_p1) & (1'd1 == p_is_write_last_fu_748_p2) & (1'd0 == empty_n_8_fu_798_p1)) | ((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd1 == tmp_rw_load_load_fu_779_p1) & (1'd0 == p_is_write_last_fu_748_p2) & (1'd1 == grp_fu_561_p1)) | ((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd1 == tmp_rw_load_load_fu_779_p1) & (1'd0 == p_is_write_last_fu_748_p2) & (1'd0 == grp_fu_561_p1)) | ((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd0 == tmp_rw_load_load_fu_779_p1) & (1'd1 == grp_fu_561_p1) & (1'd0 == grp_fu_565_p1)) | ((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd0 == tmp_rw_load_load_fu_779_p1) & (1'd0 == grp_fu_561_p1)) | ((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == brmerge82_demorgan_fu_773_p2)))) begin
        reset_8_phi_fu_509_p16 = 1'd0;
    end else if ((((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd1 == tmp_rw_load_load_fu_779_p1) & (1'd1 == p_is_write_last_fu_748_p2) & (1'd1 == empty_n_8_fu_798_p1)) | ((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == brmerge82_demorgan_fu_773_p2) & (1'd0 == tmp_rw_load_load_fu_779_p1) & (1'd1 == grp_fu_561_p1) & (1'd1 == grp_fu_565_p1)))) begin
        reset_8_phi_fu_509_p16 = 1'd1;
    end else begin
        reset_8_phi_fu_509_p16 = ap_phi_precharge_reg_pp0_iter1_reset_8_reg_505;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        reset_phi_fu_497_p4 = reset_8_phi_fu_509_p16;
    end else begin
        reset_phi_fu_497_p4 = reset_reg_493;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((1'b1 == ap_enable_reg_pp0_iter2) & (((1'b0 == host_data_pcie_write_req_apply_V_num1_status) & (1'b1 == ap_predicate_op173_write_state4)) | ((1'b0 == host_data_pcie_write_req_data_V_last1_status) & (1'b1 == ap_predicate_op175_write_state4)) | ((1'b0 == host_fin_pcie_write_req_apply_V_num1_status) & (1'b1 == ap_predicate_op179_write_state4)) | ((1'b1 == ap_predicate_op179_write_state4) & (1'b0 == host_fin_pcie_write_req_data_V_last1_status)) | ((1'b0 == host_dram_write_req_apply_V_num1_status) & (1'b1 == ap_predicate_op184_write_state4)) | ((1'b0 == host_dram_write_req_data_V_last1_status) & (1'b1 == ap_predicate_op186_write_state4)) | ((1'b0 == host_fin_pcie_write_req_apply_V_num1_status) & (1'b1 == ap_predicate_op189_write_state4)) | ((1'b0 == host_fin_pcie_write_req_data_V_last1_status) & (1'b1 == ap_predicate_op189_write_state4))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((1'b1 == ap_enable_reg_pp0_iter2) & (((1'b0 == host_data_pcie_write_req_apply_V_num1_status) & (1'b1 == ap_predicate_op173_write_state4)) | ((1'b0 == host_data_pcie_write_req_data_V_last1_status) & (1'b1 == ap_predicate_op175_write_state4)) | ((1'b0 == host_fin_pcie_write_req_apply_V_num1_status) & (1'b1 == ap_predicate_op179_write_state4)) | ((1'b1 == ap_predicate_op179_write_state4) & (1'b0 == host_fin_pcie_write_req_data_V_last1_status)) | ((1'b0 == host_dram_write_req_apply_V_num1_status) & (1'b1 == ap_predicate_op184_write_state4)) | ((1'b0 == host_dram_write_req_data_V_last1_status) & (1'b1 == ap_predicate_op186_write_state4)) | ((1'b0 == host_fin_pcie_write_req_apply_V_num1_status) & (1'b1 == ap_predicate_op189_write_state4)) | ((1'b0 == host_fin_pcie_write_req_data_V_last1_status) & (1'b1 == ap_predicate_op189_write_state4))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b1 == ap_enable_reg_pp0_iter2) & (((1'b0 == host_data_pcie_write_req_apply_V_num1_status) & (1'b1 == ap_predicate_op173_write_state4)) | ((1'b0 == host_data_pcie_write_req_data_V_last1_status) & (1'b1 == ap_predicate_op175_write_state4)) | ((1'b0 == host_fin_pcie_write_req_apply_V_num1_status) & (1'b1 == ap_predicate_op179_write_state4)) | ((1'b1 == ap_predicate_op179_write_state4) & (1'b0 == host_fin_pcie_write_req_data_V_last1_status)) | ((1'b0 == host_dram_write_req_apply_V_num1_status) & (1'b1 == ap_predicate_op184_write_state4)) | ((1'b0 == host_dram_write_req_data_V_last1_status) & (1'b1 == ap_predicate_op186_write_state4)) | ((1'b0 == host_fin_pcie_write_req_apply_V_num1_status) & (1'b1 == ap_predicate_op189_write_state4)) | ((1'b0 == host_fin_pcie_write_req_data_V_last1_status) & (1'b1 == ap_predicate_op189_write_state4))));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = (((1'b0 == host_data_pcie_write_req_apply_V_num1_status) & (1'b1 == ap_predicate_op173_write_state4)) | ((1'b0 == host_data_pcie_write_req_data_V_last1_status) & (1'b1 == ap_predicate_op175_write_state4)) | ((1'b0 == host_fin_pcie_write_req_apply_V_num1_status) & (1'b1 == ap_predicate_op179_write_state4)) | ((1'b1 == ap_predicate_op179_write_state4) & (1'b0 == host_fin_pcie_write_req_data_V_last1_status)) | ((1'b0 == host_dram_write_req_apply_V_num1_status) & (1'b1 == ap_predicate_op184_write_state4)) | ((1'b0 == host_dram_write_req_data_V_last1_status) & (1'b1 == ap_predicate_op186_write_state4)) | ((1'b0 == host_fin_pcie_write_req_apply_V_num1_status) & (1'b1 == ap_predicate_op189_write_state4)) | ((1'b0 == host_fin_pcie_write_req_data_V_last1_status) & (1'b1 == ap_predicate_op189_write_state4)));
end

always @ (*) begin
    ap_condition_333 = (1'b1 == (reqs_pipe2_read_V_sector_off_empty_n & reqs_pipe2_read_V_sector_num_empty_n & reqs_pipe2_read_V_tag_empty_n & reqs_pipe2_read_V_rw_empty_n));
end

assign ap_done = 1'b0;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_precharge_reg_pp0_iter1_reset_8_reg_505 = 'bx;

always @ (*) begin
    ap_predicate_op173_write_state4 = ((brmerge82_demorgan_reg_953 == 1'd1) & (tmp_rw_load_reg_957 == 1'd0) & (1'd1 == empty_n_7_reg_961) & (1'd1 == p_first_reg_945));
end

always @ (*) begin
    ap_predicate_op175_write_state4 = ((brmerge82_demorgan_reg_953 == 1'd1) & (tmp_rw_load_reg_957 == 1'd0) & (1'd1 == empty_n_7_reg_961));
end

always @ (*) begin
    ap_predicate_op179_write_state4 = ((brmerge82_demorgan_reg_953 == 1'd1) & (tmp_rw_load_reg_957 == 1'd0) & (1'd1 == empty_n_7_reg_961) & (1'd1 == tmp_last_2_reg_965));
end

always @ (*) begin
    ap_predicate_op184_write_state4 = ((brmerge82_demorgan_reg_953 == 1'd1) & (1'd1 == p_first_reg_945) & (1'd1 == tmp_rw_load_reg_957));
end

always @ (*) begin
    ap_predicate_op186_write_state4 = ((brmerge82_demorgan_reg_953 == 1'd1) & (1'd1 == tmp_rw_load_reg_957) & (1'd0 == p_is_write_last_reg_949) & (1'd1 == empty_n_9_reg_985));
end

always @ (*) begin
    ap_predicate_op189_write_state4 = ((brmerge82_demorgan_reg_953 == 1'd1) & (1'd1 == tmp_rw_load_reg_957) & (1'd1 == p_is_write_last_reg_949) & (1'd1 == empty_n_8_reg_994));
end

assign ap_ready = 1'b0;

assign brmerge1_fu_671_p2 = (tmp1_fu_653_p2 | tmp2_fu_665_p2);

assign brmerge82_demorgan_fu_773_p2 = (tmp3_fu_767_p2 & has_reqs_fu_368);

assign data_pipe2_read_V_data_V_read = data_pipe2_read_V_last0_update;

assign data_pipe2_read_V_last_read = data_pipe2_read_V_last0_update;

assign empty_n_6_nbread_fu_392_p5_0 = (reqs_pipe2_read_V_sector_off_empty_n & reqs_pipe2_read_V_sector_num_empty_n & reqs_pipe2_read_V_tag_empty_n & reqs_pipe2_read_V_rw_empty_n);

assign empty_n_8_fu_798_p1 = host_dram_write_resp_V_empty_n;

assign fin_write_apply_addr_2_fu_845_p2 = (tmp_addr_fu_376 + 64'd4096);

assign fin_write_apply_addr_fu_818_p2 = (tmp_addr_fu_376 + 64'd4096);

assign grp_fu_561_p1 = grp_nbread_fu_416_p3_0;

assign grp_fu_565_p1 = data_pipe2_read_V_last_dout;

assign grp_nbread_fu_416_p3_0 = (data_pipe2_read_V_last_empty_n & data_pipe2_read_V_data_V_empty_n);

assign has_reqs_0_not_fu_647_p2 = (has_reqs_fu_368 ^ 1'd1);

assign host_data_pcie_write_req_apply_V_addr_din = tmp_addr_fu_376;

assign host_data_pcie_write_req_apply_V_addr_write = host_data_pcie_write_req_apply_V_num1_update;

assign host_data_pcie_write_req_apply_V_num1_status = (host_data_pcie_write_req_apply_V_num_full_n & host_data_pcie_write_req_apply_V_addr_full_n);

assign host_data_pcie_write_req_apply_V_num_din = {{tmp_1_reg_970}, {3'd0}};

assign host_data_pcie_write_req_apply_V_num_write = host_data_pcie_write_req_apply_V_num1_update;

assign host_data_pcie_write_req_data_V_data_V_din = reg_585;

assign host_data_pcie_write_req_data_V_data_V_write = host_data_pcie_write_req_data_V_last1_update;

assign host_data_pcie_write_req_data_V_last1_status = (host_data_pcie_write_req_data_V_last_full_n & host_data_pcie_write_req_data_V_data_V_full_n);

assign host_data_pcie_write_req_data_V_last_din = tmp_last_2_reg_965;

assign host_data_pcie_write_req_data_V_last_write = host_data_pcie_write_req_data_V_last1_update;

assign host_dram_write_req_apply_V_addr_din = write_apply_addr_fu_825_p3;

assign host_dram_write_req_apply_V_addr_write = host_dram_write_req_apply_V_num1_update;

assign host_dram_write_req_apply_V_num1_status = (host_dram_write_req_apply_V_num_full_n & host_dram_write_req_apply_V_addr_full_n);

assign host_dram_write_req_apply_V_num_din = {{tmp_reg_980}, {3'd0}};

assign host_dram_write_req_apply_V_num_write = host_dram_write_req_apply_V_num1_update;

assign host_dram_write_req_data_V_data_V_din = reg_585;

assign host_dram_write_req_data_V_data_V_write = host_dram_write_req_data_V_last1_update;

assign host_dram_write_req_data_V_last1_status = (host_dram_write_req_data_V_last_full_n & host_dram_write_req_data_V_data_V_full_n);

assign host_dram_write_req_data_V_last_din = tmp_last_3_reg_989;

assign host_dram_write_req_data_V_last_write = host_dram_write_req_data_V_last1_update;

assign host_fin_pcie_write_req_apply_V_addr_write = host_fin_pcie_write_req_apply_V_num1_update;

assign host_fin_pcie_write_req_apply_V_num1_status = (host_fin_pcie_write_req_apply_V_num_full_n & host_fin_pcie_write_req_apply_V_addr_full_n);

assign host_fin_pcie_write_req_apply_V_num_din = 8'd1;

assign host_fin_pcie_write_req_apply_V_num_write = host_fin_pcie_write_req_apply_V_num1_update;

assign host_fin_pcie_write_req_data_V_data_V_din = 512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095;

assign host_fin_pcie_write_req_data_V_data_V_write = host_fin_pcie_write_req_data_V_last1_update;

assign host_fin_pcie_write_req_data_V_last1_status = (host_fin_pcie_write_req_data_V_last_full_n & host_fin_pcie_write_req_data_V_data_V_full_n);

assign host_fin_pcie_write_req_data_V_last_din = 1'd1;

assign host_fin_pcie_write_req_data_V_last_write = host_fin_pcie_write_req_data_V_last1_update;

assign not_reset_fu_620_p2 = (reset_phi_fu_497_p4 ^ 1'd1);

assign p_first_fu_741_p2 = (reset_reg_493 | first_fu_372);

assign p_has_data_valid_fu_633_p2 = (has_data_valid_fu_364 & not_reset_fu_620_p2);

assign p_has_kbu_fu_640_p2 = (has_kbuf_addr_fu_360 & not_reset_fu_620_p2);

assign p_has_reqs_fu_626_p2 = (has_reqs_fu_368 & not_reset_fu_620_p2);

assign p_is_write_last_fu_748_p2 = (tmp_last_fu_356 & not_reset_reg_921);

assign reqs_pipe2_read_V_rw_read = reqs_pipe2_read_V_rw0_update;

assign reqs_pipe2_read_V_sector_num_read = reqs_pipe2_read_V_rw0_update;

assign reqs_pipe2_read_V_sector_off_read = reqs_pipe2_read_V_rw0_update;

assign reqs_pipe2_read_V_tag_read = reqs_pipe2_read_V_rw0_update;

assign tmp1_fu_653_p2 = (reset_phi_fu_497_p4 | has_reqs_0_not_fu_647_p2);

assign tmp2_demorgan_fu_659_p2 = (has_data_valid_fu_364 & has_kbuf_addr_fu_360);

assign tmp2_fu_665_p2 = (tmp2_demorgan_fu_659_p2 ^ 1'd1);

assign tmp3_fu_767_p2 = (has_data_valid_fu_364 & has_kbuf_addr_fu_360);

assign tmp_1_fu_782_p1 = tmp_sector_num_fu_384[4:0];

assign tmp_fu_789_p1 = tmp_sector_num_fu_384[4:0];

assign tmp_rw_load_load_fu_779_p1 = tmp_rw_fu_380;

assign write_apply_addr_fu_825_p3 = {{tmp_sector_off_load_reg_975}, {9'd0}};

endmodule //pipe2_data_handler
