// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="unused_channel_preserver,hls_ip_2017_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-2-i,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.594000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=5,HLS_SYN_LUT=105}" *)

module unused_channel_preserver (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
ap_continue,
        ap_idle,
        ap_ready,
        device_dram_write_req_data_V_last_din,
        device_dram_write_req_data_V_last_full_n,
        device_dram_write_req_data_V_last_write,
        device_dram_write_req_data_V_data_V_din,
        device_dram_write_req_data_V_data_V_full_n,
        device_dram_write_req_data_V_data_V_write,
        device_dram_write_req_apply_V_num_din,
        device_dram_write_req_apply_V_num_full_n,
        device_dram_write_req_apply_V_num_write,
        device_dram_write_req_apply_V_addr_din,
        device_dram_write_req_apply_V_addr_full_n,
        device_dram_write_req_apply_V_addr_write,
        preserver_cheat_signals_V_dout,
        preserver_cheat_signals_V_empty_n,
        preserver_cheat_signals_V_read
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output ap_ready; output ap_continue;
output   device_dram_write_req_data_V_last_din;
input   device_dram_write_req_data_V_last_full_n;
output   device_dram_write_req_data_V_last_write;
output  [511:0] device_dram_write_req_data_V_data_V_din;
input   device_dram_write_req_data_V_data_V_full_n;
output   device_dram_write_req_data_V_data_V_write;
output  [7:0] device_dram_write_req_apply_V_num_din;
input   device_dram_write_req_apply_V_num_full_n;
output   device_dram_write_req_apply_V_num_write;
output  [63:0] device_dram_write_req_apply_V_addr_din;
input   device_dram_write_req_apply_V_addr_full_n;
output   device_dram_write_req_apply_V_addr_write;
input   preserver_cheat_signals_V_dout;
input   preserver_cheat_signals_V_empty_n;
output   preserver_cheat_signals_V_read;

reg ap_idle;
reg preserver_cheat_signals_V_read;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    device_dram_write_req_data_V_last_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] empty_n_reg_148;
reg    device_dram_write_req_data_V_data_V_blk_n;
reg    device_dram_write_req_apply_V_num_blk_n;
reg    device_dram_write_req_apply_V_addr_blk_n;
wire    ap_block_state2_pp0_stage0_iter0;
wire    device_dram_write_req_data_V_last1_status;
wire    device_dram_write_req_apply_V_num1_status;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg    ap_enable_reg_pp0_iter0;
reg    ap_block_pp0_stage0_subdone;
reg    device_dram_write_req_data_V_last1_update;
reg    ap_block_pp0_stage0_01001;
reg    device_dram_write_req_apply_V_num1_update;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_subdone == 1'b0)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        empty_n_reg_148 <= preserver_cheat_signals_V_empty_n;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0 == 1'b0) & (empty_n_reg_148 == 1'd1))) begin
        device_dram_write_req_apply_V_addr_blk_n = device_dram_write_req_apply_V_addr_full_n;
    end else begin
        device_dram_write_req_apply_V_addr_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (empty_n_reg_148 == 1'd1) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        device_dram_write_req_apply_V_num1_update = 1'b1;
    end else begin
        device_dram_write_req_apply_V_num1_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0 == 1'b0) & (empty_n_reg_148 == 1'd1))) begin
        device_dram_write_req_apply_V_num_blk_n = device_dram_write_req_apply_V_num_full_n;
    end else begin
        device_dram_write_req_apply_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0 == 1'b0) & (empty_n_reg_148 == 1'd1))) begin
        device_dram_write_req_data_V_data_V_blk_n = device_dram_write_req_data_V_data_V_full_n;
    end else begin
        device_dram_write_req_data_V_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (empty_n_reg_148 == 1'd1) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        device_dram_write_req_data_V_last1_update = 1'b1;
    end else begin
        device_dram_write_req_data_V_last1_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0 == 1'b0) & (empty_n_reg_148 == 1'd1))) begin
        device_dram_write_req_data_V_last_blk_n = device_dram_write_req_data_V_last_full_n;
    end else begin
        device_dram_write_req_data_V_last_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == preserver_cheat_signals_V_empty_n))) begin
        preserver_cheat_signals_V_read = 1'b1;
    end else begin
        preserver_cheat_signals_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((1'b1 == ap_enable_reg_pp0_iter1) & (((empty_n_reg_148 == 1'd1) & (1'b0 == device_dram_write_req_data_V_last1_status)) | ((empty_n_reg_148 == 1'd1) & (1'b0 == device_dram_write_req_apply_V_num1_status))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((1'b1 == ap_enable_reg_pp0_iter1) & (((empty_n_reg_148 == 1'd1) & (1'b0 == device_dram_write_req_data_V_last1_status)) | ((empty_n_reg_148 == 1'd1) & (1'b0 == device_dram_write_req_apply_V_num1_status))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b1 == ap_enable_reg_pp0_iter1) & (((empty_n_reg_148 == 1'd1) & (1'b0 == device_dram_write_req_data_V_last1_status)) | ((empty_n_reg_148 == 1'd1) & (1'b0 == device_dram_write_req_apply_V_num1_status))));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((empty_n_reg_148 == 1'd1) & (1'b0 == device_dram_write_req_data_V_last1_status)) | ((empty_n_reg_148 == 1'd1) & (1'b0 == device_dram_write_req_apply_V_num1_status)));
end

assign ap_done = 1'b0;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = 1'b0;

assign device_dram_write_req_apply_V_addr_din = 64'd0;

assign device_dram_write_req_apply_V_addr_write = device_dram_write_req_apply_V_num1_update;

assign device_dram_write_req_apply_V_num1_status = (device_dram_write_req_apply_V_num_full_n & device_dram_write_req_apply_V_addr_full_n);

assign device_dram_write_req_apply_V_num_din = 8'd0;

assign device_dram_write_req_apply_V_num_write = device_dram_write_req_apply_V_num1_update;

assign device_dram_write_req_data_V_data_V_din = 512'd0;

assign device_dram_write_req_data_V_data_V_write = device_dram_write_req_data_V_last1_update;

assign device_dram_write_req_data_V_last1_status = (device_dram_write_req_data_V_last_full_n & device_dram_write_req_data_V_data_V_full_n);

assign device_dram_write_req_data_V_last_din = 1'd0;

assign device_dram_write_req_data_V_last_write = device_dram_write_req_data_V_last1_update;

endmodule //unused_channel_preserver
